Desktop TUI: tui::Label Class Reference
tui::Label Class Reference
Label widget - displays text.
#include <label.hpp>
Public Types
enum Align {
Left ,
Center ,
Right
}
Public Member Functions
Label ()=default
Label (const std::string &text, const Style &style=Style::Default())
void set_text (const std::string &text)
std::string text () const
void set_style (const Style &s)
void set_align (Align a)
void render (Renderer &r) override
Public Member Functions inherited from tui::Widget
Widget ()=default
virtual ~Widget ()=default
virtual void set_bounds (const Rect &r)
virtual Rect bounds () const
virtual int x () const
virtual int y () const
virtual int width () const
virtual int height () const
virtual void show ()
virtual void hide ()
virtual bool visible () const
virtual void focus ()
virtual void blur ()
virtual bool focused () const
virtual bool can_focus () const
virtual void set_focusable (bool f)
virtual void render (Renderer &r)=0
virtual bool handle_event (const Event &e)
virtual void on_resize (int cols, int rows)
void on_click (std::function< void()> cb)
Additional Inherited Members
Protected Member Functions inherited from tui::Widget
virtual void on_focus ()
virtual void on_blur ()
void emit_click ()
Protected Attributes inherited from tui::Widget
Rect bounds_
bool visible_ = true
bool focused_ = false
bool focusable_ = false
std::function< void()> on_click_
Detailed Description
Label widget - displays text.
Definition at line 13 of file label.hpp.
Member Enumeration Documentation
Align
enum tui::Label::Align
Enumerator
Left
Center
Right
Definition at line 15 of file label.hpp.
Constructor & Destructor Documentation
Label() [1/2]
tui::Label::Label () default
Label() [2/2]
tui::Label::Label (const std::string & text, const Style & style = Style::Default()) inline
Definition at line 18 of file label.hpp.
Member Function Documentation
render()
void tui::Label::render (Renderer & r) inline override virtual
Implements tui::Widget.
Definition at line 27 of file label.hpp.
References tui::Widget::bounds_, Center, tui::Rect::h, Left, Right, tui::Widget::visible_, tui::Rect::w, tui::word_wrap(), tui::Renderer::write(), tui::Renderer::write_center(), tui::Renderer::write_right(), tui::Rect::x, tui::Rect::y, and tui::Widget::y().
set_align()
void tui::Label::set_align (Align a) inline
Definition at line 25 of file label.hpp.
set_style()
void tui::Label::set_style (const Style & s) inline
Definition at line 24 of file label.hpp.
set_text()
void tui::Label::set_text (const std::string & text) inline
Definition at line 21 of file label.hpp.
References text().
text()
std::string tui::Label::text () const inline
Definition at line 22 of file label.hpp.
Referenced by set_text().
The documentation for this class was generated from the following file:
include/ui/label.hpp