Desktop TUI: tui::List Class Reference
tui::List Class Reference
List widget - scrollable list of items.
#include <list.hpp>
Public Member Functions
List ()
void add_item (const std::string &text)
void set_items (std::vector< std::string > items)
const std::vector< std::string > & items () const
int selected () const
void set_selected (int idx)
void on_select (std::function< void(int)> cb)
void render (Renderer &r) override
bool handle_event (const Event &e) override
void clear ()
int size () const
Public Member Functions inherited from tui::Widget
Widget ()=default
virtual ~Widget ()=default
virtual void set_bounds (const Rect &r)
virtual Rect bounds () const
virtual int x () const
virtual int y () const
virtual int width () const
virtual int height () const
virtual void show ()
virtual void hide ()
virtual bool visible () const
virtual void focus ()
virtual void blur ()
virtual bool focused () const
virtual bool can_focus () const
virtual void set_focusable (bool f)
virtual void render (Renderer &r)=0
virtual bool handle_event (const Event &e)
virtual void on_resize (int cols, int rows)
void on_click (std::function< void()> cb)
Additional Inherited Members
Protected Member Functions inherited from tui::Widget
virtual void on_focus ()
virtual void on_blur ()
void emit_click ()
Protected Attributes inherited from tui::Widget
Rect bounds_
bool visible_ = true
bool focused_ = false
bool focusable_ = false
std::function< void()> on_click_
Detailed Description
List widget - scrollable list of items.
Definition at line 13 of file list.hpp.
Constructor & Destructor Documentation
List()
tui::List::List () inline
Definition at line 15 of file list.hpp.
References tui::Widget::focusable_.
Member Function Documentation
add_item()
void tui::List::add_item (const std::string & text) inline
Definition at line 17 of file list.hpp.
clear()
void tui::List::clear () inline
Definition at line 101 of file list.hpp.
handle_event()
bool tui::List::handle_event (const Event & e) inline override virtual
Reimplemented from tui::Widget.
Definition at line 56 of file list.hpp.
References tui::Keys::ArrowDown, tui::Keys::ArrowUp, tui::Widget::bounds_, tui::Widget::emit_click(), tui::Keys::End, tui::Keys::Enter, tui::Widget::focused_, tui::Rect::h, tui::Keys::Home, tui::Event::key_code, tui::KeyPress, tui::Keys::PageDown, tui::Keys::PageUp, set_selected(), tui::Event::type, and tui::Widget::visible_.
items()
const std::vector< std::string > & tui::List::items () const inline
Definition at line 19 of file list.hpp.
Referenced by set_items().
on_select()
void tui::List::on_select (std::function< void(int)> cb) inline
Definition at line 29 of file list.hpp.
render()
void tui::List::render (Renderer & r) inline override virtual
Implements tui::Widget.
Definition at line 31 of file list.hpp.
References tui::Widget::bounds_, tui::Style::Default(), tui::Styles::Dim(), tui::display_width(), tui::Widget::focused_, tui::Rect::h, tui::Styles::Selected(), tui::truncate(), tui::Widget::visible_, tui::Rect::w, tui::Renderer::write(), tui::Rect::x, and tui::Rect::y.
selected()
int tui::List::selected () const inline
Definition at line 21 of file list.hpp.
set_items()
void tui::List::set_items (std::vector< std::string > items) inline
Definition at line 18 of file list.hpp.
References items().
set_selected()
void tui::List::set_selected (int idx) inline
Definition at line 22 of file list.hpp.
Referenced by handle_event().
size()
int tui::List::size () const inline
Definition at line 102 of file list.hpp.
The documentation for this class was generated from the following file:
include/ui/list.hpp