Desktop TUI: tui::ITerminal Class Reference
tui::ITerminal Class Reference abstract
Abstract terminal interface.
#include <terminal.hpp>
Public Member Functions
virtual ~ITerminal ()=default
virtual bool init ()=0
virtual void shutdown ()=0
virtual void clear ()=0
virtual void flush ()=0
virtual void sync ()=0
virtual void cursor_hide ()=0
virtual void cursor_show ()=0
virtual void cursor_move (int x, int y)=0
virtual void cursor_save ()=0
virtual void cursor_restore ()=0
virtual int cols () const =0
virtual int rows () const =0
virtual Rect bounds () const
virtual void write (const std::string &text)=0
virtual void write_at (int x, int y, const std::string &text)=0
virtual void write_styled (const std::string &text, const Style &style)=0
virtual void write_styled_at (int x, int y, const std::string &text, const Style &style)=0
virtual void fill (int x, int y, int w, int h, char ch, const Style &style)=0
virtual void clear_region (int x, int y, int w, int h)=0
virtual void draw_hline (int x, int y, int w, const Style &style)=0
virtual void draw_vline (int x, int y, int h, const Style &style)=0
virtual void draw_rect (int x, int y, int w, int h, const Style &style)=0
virtual void draw_box (int x, int y, int w, int h, const Style &border_style, const Style &fill_style)
virtual void enter_raw_mode ()=0
virtual void leave_raw_mode ()=0
virtual void enter_alternate_screen ()=0
virtual void leave_alternate_screen ()=0
virtual void set_title (const std::string &title)=0
virtual TerminalCaps caps () const =0
virtual bool has_cap (TerminalCaps cap) const
virtual std::string term_type () const =0
virtual bool check_resize (int &new_cols, int &new_rows)
Detailed Description
Abstract terminal interface.
Definition at line 31 of file terminal.hpp.
Constructor & Destructor Documentation
~ITerminal()
virtual tui::ITerminal::~ITerminal () virtual default
Member Function Documentation
bounds()
virtual Rect tui::ITerminal::bounds () const inline virtual
Definition at line 54 of file terminal.hpp.
References cols(), and rows().
caps()
virtual TerminalCaps tui::ITerminal::caps () const pure virtual
Implemented in tui::GenericTerminal, tui::PosixTerminal, and tui::WindowsTerminal.
Referenced by has_cap().
check_resize()
virtual bool tui::ITerminal::check_resize (int & new_cols, int & new_rows) inline virtual
Reimplemented in tui::PosixTerminal.
Definition at line 102 of file terminal.hpp.
Referenced by TUIShell::run().
clear()
virtual void tui::ITerminal::clear () pure virtual
Implemented in tui::GenericTerminal, tui::PosixTerminal, and tui::WindowsTerminal.
clear_region()
virtual void tui::ITerminal::clear_region (int x, int y, int w, int h) pure virtual
Implemented in tui::GenericTerminal, tui::PosixTerminal, and tui::WindowsTerminal.
cols()
virtual int tui::ITerminal::cols () const pure virtual
Implemented in tui::GenericTerminal, tui::PosixTerminal, and tui::WindowsTerminal.
Referenced by bounds(), and tui::Renderer::init().
cursor_hide()
virtual void tui::ITerminal::cursor_hide () pure virtual
Implemented in tui::GenericTerminal, tui::PosixTerminal, and tui::WindowsTerminal.
Referenced by tui::Renderer::flush(), and TUIShell::init().
cursor_move()
virtual void tui::ITerminal::cursor_move (int x, int y) pure virtual
Implemented in tui::GenericTerminal, tui::PosixTerminal, and tui::WindowsTerminal.
Referenced by tui::Renderer::flush().
cursor_restore()
virtual void tui::ITerminal::cursor_restore () pure virtual
Implemented in tui::GenericTerminal, tui::PosixTerminal, and tui::WindowsTerminal.
cursor_save()
virtual void tui::ITerminal::cursor_save () pure virtual
Implemented in tui::GenericTerminal, tui::PosixTerminal, and tui::WindowsTerminal.
cursor_show()
virtual void tui::ITerminal::cursor_show () pure virtual
Implemented in tui::GenericTerminal, tui::PosixTerminal, and tui::WindowsTerminal.
Referenced by tui::Renderer::flush(), and TUIShell::shutdown().
draw_box()
virtual void tui::ITerminal::draw_box (int x, int y, int w, int h, const Style & border_style, const Style & fill_style) inline virtual
Definition at line 70 of file terminal.hpp.
References draw_rect(), and write_styled_at().
draw_hline()
virtual void tui::ITerminal::draw_hline (int x, int y, int w, const Style & style) pure virtual
Implemented in tui::GenericTerminal, tui::PosixTerminal, and tui::WindowsTerminal.
draw_rect()
virtual void tui::ITerminal::draw_rect (int x, int y, int w, int h, const Style & style) pure virtual
Implemented in tui::GenericTerminal, tui::PosixTerminal, and tui::WindowsTerminal.
Referenced by draw_box().
draw_vline()
virtual void tui::ITerminal::draw_vline (int x, int y, int h, const Style & style) pure virtual
Implemented in tui::GenericTerminal, tui::PosixTerminal, and tui::WindowsTerminal.
enter_alternate_screen()
virtual void tui::ITerminal::enter_alternate_screen () pure virtual
Implemented in tui::GenericTerminal, tui::PosixTerminal, and tui::WindowsTerminal.
Referenced by TUIShell::init().
enter_raw_mode()
virtual void tui::ITerminal::enter_raw_mode () pure virtual
Implemented in tui::GenericTerminal, tui::PosixTerminal, and tui::WindowsTerminal.
Referenced by TUIShell::init().
fill()
virtual void tui::ITerminal::fill (int x, int y, int w, int h, char ch, const Style & style) pure virtual
Implemented in tui::GenericTerminal, tui::PosixTerminal, and tui::WindowsTerminal.
flush()
virtual void tui::ITerminal::flush () pure virtual
Implemented in tui::GenericTerminal, tui::PosixTerminal, and tui::WindowsTerminal.
Referenced by tui::Renderer::flush().
has_cap()
virtual bool tui::ITerminal::has_cap (TerminalCaps cap) const inline virtual
Definition at line 95 of file terminal.hpp.
References caps(), and tui::None.
Referenced by tui::Renderer::draw_border(), tui::Renderer::draw_box(), tui::PosixTerminal::draw_hline(), tui::PosixTerminal::draw_rect(), and tui::PosixTerminal::draw_vline().
init()
virtual bool tui::ITerminal::init () pure virtual
Implemented in tui::GenericTerminal, tui::PosixTerminal, and tui::WindowsTerminal.
Referenced by TUIShell::init().
leave_alternate_screen()
virtual void tui::ITerminal::leave_alternate_screen () pure virtual
Implemented in tui::GenericTerminal, tui::PosixTerminal, and tui::WindowsTerminal.
Referenced by TUIShell::shutdown().
leave_raw_mode()
virtual void tui::ITerminal::leave_raw_mode () pure virtual
Implemented in tui::GenericTerminal, tui::PosixTerminal, and tui::WindowsTerminal.
Referenced by TUIShell::shutdown().
rows()
virtual int tui::ITerminal::rows () const pure virtual
Implemented in tui::GenericTerminal, tui::PosixTerminal, and tui::WindowsTerminal.
Referenced by bounds(), and tui::Renderer::init().
set_title()
virtual void tui::ITerminal::set_title (const std::string & title) pure virtual
Implemented in tui::GenericTerminal, tui::PosixTerminal, and tui::WindowsTerminal.
Referenced by TUIShell::init().
shutdown()
virtual void tui::ITerminal::shutdown () pure virtual
Implemented in tui::GenericTerminal, tui::PosixTerminal, and tui::WindowsTerminal.
Referenced by TUIShell::shutdown().
sync()
virtual void tui::ITerminal::sync () pure virtual
Implemented in tui::GenericTerminal, tui::PosixTerminal, and tui::WindowsTerminal.
term_type()
virtual std::string tui::ITerminal::term_type () const pure virtual
Implemented in tui::GenericTerminal, tui::PosixTerminal, and tui::WindowsTerminal.
write()
virtual void tui::ITerminal::write (const std::string & text) pure virtual
Implemented in tui::GenericTerminal, tui::PosixTerminal, and tui::WindowsTerminal.
Referenced by tui::Renderer::flush().
write_at()
virtual void tui::ITerminal::write_at (int x, int y, const std::string & text) pure virtual
Implemented in tui::GenericTerminal, tui::PosixTerminal, and tui::WindowsTerminal.
write_styled()
virtual void tui::ITerminal::write_styled (const std::string & text, const Style & style) pure virtual
Implemented in tui::GenericTerminal, tui::PosixTerminal, and tui::WindowsTerminal.
write_styled_at()
virtual void tui::ITerminal::write_styled_at (int x, int y, const std::string & text, const Style & style) pure virtual
Implemented in tui::GenericTerminal, tui::PosixTerminal, and tui::WindowsTerminal.
Referenced by draw_box().
The documentation for this class was generated from the following file:
include/platform/terminal.hpp