Desktop TUI: tui::PosixTerminal Class Reference
tui::PosixTerminal Class Reference
Public Member Functions
PosixTerminal ()
~PosixTerminal () override
bool init () override
bool check_resize (int &new_cols, int &new_rows)
void shutdown () override
void clear () override
void flush () override
void sync () override
void cursor_hide () override
void cursor_show () override
void cursor_move (int x, int y) override
void cursor_save () override
void cursor_restore () override
int cols () const override
int rows () const override
void write (const std::string &text) override
void write_raw (const std::string &text)
void write_at (int x, int y, const std::string &text) override
void write_styled (const std::string &text, const Style &style) override
void write_styled_at (int x, int y, const std::string &text, const Style &style) override
void fill (int x, int y, int w, int h, char ch, const Style &style) override
void clear_region (int x, int y, int w, int h) override
void draw_hline (int x, int y, int w, const Style &style) override
void draw_vline (int x, int y, int h, const Style &style) override
void draw_rect (int x, int y, int w, int h, const Style &style) override
void enter_raw_mode () override
void leave_raw_mode () override
void enter_alternate_screen () override
void leave_alternate_screen () override
void set_title (const std::string &title) override
TerminalCaps caps () const override
std::string term_type () const override
Public Member Functions inherited from tui::ITerminal
virtual ~ITerminal ()=default
virtual bool init ()=0
virtual void shutdown ()=0
virtual void clear ()=0
virtual void flush ()=0
virtual void sync ()=0
virtual void cursor_hide ()=0
virtual void cursor_show ()=0
virtual void cursor_move (int x, int y)=0
virtual void cursor_save ()=0
virtual void cursor_restore ()=0
virtual int cols () const =0
virtual int rows () const =0
virtual Rect bounds () const
virtual void write (const std::string &text)=0
virtual void write_at (int x, int y, const std::string &text)=0
virtual void write_styled (const std::string &text, const Style &style)=0
virtual void write_styled_at (int x, int y, const std::string &text, const Style &style)=0
virtual void fill (int x, int y, int w, int h, char ch, const Style &style)=0
virtual void clear_region (int x, int y, int w, int h)=0
virtual void draw_hline (int x, int y, int w, const Style &style)=0
virtual void draw_vline (int x, int y, int h, const Style &style)=0
virtual void draw_rect (int x, int y, int w, int h, const Style &style)=0
virtual void draw_box (int x, int y, int w, int h, const Style &border_style, const Style &fill_style)
virtual void enter_raw_mode ()=0
virtual void leave_raw_mode ()=0
virtual void enter_alternate_screen ()=0
virtual void leave_alternate_screen ()=0
virtual void set_title (const std::string &title)=0
virtual TerminalCaps caps () const =0
virtual bool has_cap (TerminalCaps cap) const
virtual std::string term_type () const =0
virtual bool check_resize (int &new_cols, int &new_rows)
Detailed Description
Definition at line 25 of file terminal_posix.cpp.
Constructor & Destructor Documentation
PosixTerminal()
tui::PosixTerminal::PosixTerminal () inline
Definition at line 27 of file terminal_posix.cpp.
~PosixTerminal()
tui::PosixTerminal::~PosixTerminal () inline override
Definition at line 39 of file terminal_posix.cpp.
References cursor_show(), tui::g_is_initialized, leave_alternate_screen(), and leave_raw_mode().
Member Function Documentation
caps()
TerminalCaps tui::PosixTerminal::caps () const inline override virtual
Implements tui::ITerminal.
Definition at line 274 of file terminal_posix.cpp.
check_resize()
bool tui::PosixTerminal::check_resize (int & new_cols, int & new_rows) inline virtual
Reimplemented from tui::ITerminal.
Definition at line 82 of file terminal_posix.cpp.
References tui::g_resize_pending.
clear()
void tui::PosixTerminal::clear () inline override virtual
Implements tui::ITerminal.
Definition at line 102 of file terminal_posix.cpp.
References write().
clear_region()
void tui::PosixTerminal::clear_region (int x, int y, int w, int h) inline override virtual
Implements tui::ITerminal.
Definition at line 160 of file terminal_posix.cpp.
References tui::Style::Default(), and fill().
cols()
int tui::PosixTerminal::cols () const inline override virtual
Implements tui::ITerminal.
Definition at line 126 of file terminal_posix.cpp.
cursor_hide()
void tui::PosixTerminal::cursor_hide () inline override virtual
Implements tui::ITerminal.
Definition at line 114 of file terminal_posix.cpp.
References write().
cursor_move()
void tui::PosixTerminal::cursor_move (int x, int y) inline override virtual
Implements tui::ITerminal.
Definition at line 117 of file terminal_posix.cpp.
References write_raw().
Referenced by write_at(), and write_styled_at().
cursor_restore()
void tui::PosixTerminal::cursor_restore () inline override virtual
Implements tui::ITerminal.
Definition at line 124 of file terminal_posix.cpp.
References write().
cursor_save()
void tui::PosixTerminal::cursor_save () inline override virtual
Implements tui::ITerminal.
Definition at line 123 of file terminal_posix.cpp.
References write().
cursor_show()
void tui::PosixTerminal::cursor_show () inline override virtual
Implements tui::ITerminal.
Definition at line 115 of file terminal_posix.cpp.
References write().
Referenced by shutdown(), and ~PosixTerminal().
draw_hline()
void tui::PosixTerminal::draw_hline (int x, int y, int w, const Style & style) inline override virtual
Implements tui::ITerminal.
Definition at line 164 of file terminal_posix.cpp.
References tui::BoxDrawing, tui::ITerminal::has_cap(), and write_styled_at().
draw_rect()
void tui::PosixTerminal::draw_rect (int x, int y, int w, int h, const Style & style) inline override virtual
Implements tui::ITerminal.
Definition at line 178 of file terminal_posix.cpp.
References tui::BoxDrawing, tui::ITerminal::has_cap(), and write_styled_at().
draw_vline()
void tui::PosixTerminal::draw_vline (int x, int y, int h, const Style & style) inline override virtual
Implements tui::ITerminal.
Definition at line 171 of file terminal_posix.cpp.
References tui::BoxDrawing, tui::ITerminal::has_cap(), and write_styled_at().
enter_alternate_screen()
void tui::PosixTerminal::enter_alternate_screen () inline override virtual
Implements tui::ITerminal.
Definition at line 233 of file terminal_posix.cpp.
References flush(), and write().
enter_raw_mode()
void tui::PosixTerminal::enter_raw_mode () inline override virtual
Implements tui::ITerminal.
Definition at line 207 of file terminal_posix.cpp.
References flush(), and write().
fill()
void tui::PosixTerminal::fill (int x, int y, int w, int h, char ch, const Style & style) inline override virtual
Implements tui::ITerminal.
Definition at line 153 of file terminal_posix.cpp.
References write_styled_at().
Referenced by clear_region().
flush()
void tui::PosixTerminal::flush () inline override virtual
Implements tui::ITerminal.
Definition at line 106 of file terminal_posix.cpp.
Referenced by enter_alternate_screen(), enter_raw_mode(), leave_alternate_screen(), shutdown(), and sync().
init()
bool tui::PosixTerminal::init () inline override virtual
Implements tui::ITerminal.
Definition at line 47 of file terminal_posix.cpp.
References tui::g_is_initialized.
leave_alternate_screen()
void tui::PosixTerminal::leave_alternate_screen () inline override virtual
Implements tui::ITerminal.
Definition at line 239 of file terminal_posix.cpp.
References flush(), and write().
Referenced by shutdown(), and ~PosixTerminal().
leave_raw_mode()
void tui::PosixTerminal::leave_raw_mode () inline override virtual
Implements tui::ITerminal.
Definition at line 225 of file terminal_posix.cpp.
References write().
Referenced by shutdown(), and ~PosixTerminal().
rows()
int tui::PosixTerminal::rows () const inline override virtual
Implements tui::ITerminal.
Definition at line 127 of file terminal_posix.cpp.
set_title()
void tui::PosixTerminal::set_title (const std::string & title) inline override virtual
Implements tui::ITerminal.
Definition at line 245 of file terminal_posix.cpp.
References write().
shutdown()
void tui::PosixTerminal::shutdown () inline override virtual
Implements tui::ITerminal.
Definition at line 94 of file terminal_posix.cpp.
References cursor_show(), flush(), leave_alternate_screen(), leave_raw_mode(), and write().
sync()
void tui::PosixTerminal::sync () inline override virtual
Implements tui::ITerminal.
Definition at line 110 of file terminal_posix.cpp.
References flush().
term_type()
std::string tui::PosixTerminal::term_type () const inline override virtual
Implements tui::ITerminal.
Definition at line 275 of file terminal_posix.cpp.
write()
void tui::PosixTerminal::write (const std::string & text) inline override virtual
Implements tui::ITerminal.
Definition at line 129 of file terminal_posix.cpp.
Referenced by clear(), cursor_hide(), cursor_restore(), cursor_save(), cursor_show(), enter_alternate_screen(), enter_raw_mode(), leave_alternate_screen(), leave_raw_mode(), set_title(), shutdown(), write_at(), and write_styled().
write_at()
void tui::PosixTerminal::write_at (int x, int y, const std::string & text) inline override virtual
Implements tui::ITerminal.
Definition at line 137 of file terminal_posix.cpp.
References cursor_move(), and write().
write_raw()
void tui::PosixTerminal::write_raw (const std::string & text) inline
Definition at line 133 of file terminal_posix.cpp.
Referenced by cursor_move().
write_styled()
void tui::PosixTerminal::write_styled (const std::string & text, const Style & style) inline override virtual
Implements tui::ITerminal.
Definition at line 142 of file terminal_posix.cpp.
References write().
Referenced by write_styled_at().
write_styled_at()
void tui::PosixTerminal::write_styled_at (int x, int y, const std::string & text, const Style & style) inline override virtual
Implements tui::ITerminal.
Definition at line 148 of file terminal_posix.cpp.
References cursor_move(), and write_styled().
Referenced by draw_hline(), draw_rect(), draw_vline(), and fill().
The documentation for this class was generated from the following file:
src/platform/terminal_posix.cpp