Desktop TUI: tui::GenericTerminal Class Reference
tui::GenericTerminal Class Reference
Public Member Functions
GenericTerminal ()
bool init () override
void shutdown () override
void clear () override
void flush () override
void sync () override
void cursor_hide () override
void cursor_show () override
void cursor_move (int x, int y) override
void cursor_save () override
void cursor_restore () override
int cols () const override
int rows () const override
void write (const std::string &text) override
void write_at (int x, int y, const std::string &text) override
void write_styled (const std::string &text, const Style &style) override
void write_styled_at (int x, int y, const std::string &text, const Style &style) override
void fill (int x, int y, int w, int h, char ch, const Style &style) override
void clear_region (int x, int y, int w, int h) override
void draw_hline (int x, int y, int w, const Style &style) override
void draw_vline (int x, int y, int h, const Style &style) override
void draw_rect (int x, int y, int w, int h, const Style &style) override
void enter_raw_mode () override
void leave_raw_mode () override
void enter_alternate_screen () override
void leave_alternate_screen () override
void set_title (const std::string &title) override
TerminalCaps caps () const override
std::string term_type () const override
Public Member Functions inherited from tui::ITerminal
virtual ~ITerminal ()=default
virtual bool init ()=0
virtual void shutdown ()=0
virtual void clear ()=0
virtual void flush ()=0
virtual void sync ()=0
virtual void cursor_hide ()=0
virtual void cursor_show ()=0
virtual void cursor_move (int x, int y)=0
virtual void cursor_save ()=0
virtual void cursor_restore ()=0
virtual int cols () const =0
virtual int rows () const =0
virtual Rect bounds () const
virtual void write (const std::string &text)=0
virtual void write_at (int x, int y, const std::string &text)=0
virtual void write_styled (const std::string &text, const Style &style)=0
virtual void write_styled_at (int x, int y, const std::string &text, const Style &style)=0
virtual void fill (int x, int y, int w, int h, char ch, const Style &style)=0
virtual void clear_region (int x, int y, int w, int h)=0
virtual void draw_hline (int x, int y, int w, const Style &style)=0
virtual void draw_vline (int x, int y, int h, const Style &style)=0
virtual void draw_rect (int x, int y, int w, int h, const Style &style)=0
virtual void draw_box (int x, int y, int w, int h, const Style &border_style, const Style &fill_style)
virtual void enter_raw_mode ()=0
virtual void leave_raw_mode ()=0
virtual void enter_alternate_screen ()=0
virtual void leave_alternate_screen ()=0
virtual void set_title (const std::string &title)=0
virtual TerminalCaps caps () const =0
virtual bool has_cap (TerminalCaps cap) const
virtual std::string term_type () const =0
virtual bool check_resize (int &new_cols, int &new_rows)
Detailed Description
Definition at line 9 of file terminal_generic.cpp.
Constructor & Destructor Documentation
GenericTerminal()
tui::GenericTerminal::GenericTerminal () inline
Definition at line 11 of file terminal_generic.cpp.
Member Function Documentation
caps()
TerminalCaps tui::GenericTerminal::caps () const inline override virtual
Implements tui::ITerminal.
Definition at line 163 of file terminal_generic.cpp.
References tui::AnsiColors.
clear()
void tui::GenericTerminal::clear () inline override virtual
Implements tui::ITerminal.
Definition at line 31 of file terminal_generic.cpp.
References write().
clear_region()
void tui::GenericTerminal::clear_region (int x, int y, int w, int h) inline override virtual
Implements tui::ITerminal.
Definition at line 77 of file terminal_generic.cpp.
References tui::Style::Default(), and fill().
cols()
int tui::GenericTerminal::cols () const inline override virtual
Implements tui::ITerminal.
Definition at line 47 of file terminal_generic.cpp.
cursor_hide()
void tui::GenericTerminal::cursor_hide () inline override virtual
Implements tui::ITerminal.
Definition at line 35 of file terminal_generic.cpp.
References write().
cursor_move()
void tui::GenericTerminal::cursor_move (int x, int y) inline override virtual
Implements tui::ITerminal.
Definition at line 38 of file terminal_generic.cpp.
References write().
Referenced by write_at(), and write_styled_at().
cursor_restore()
void tui::GenericTerminal::cursor_restore () inline override virtual
Implements tui::ITerminal.
Definition at line 45 of file terminal_generic.cpp.
References write().
cursor_save()
void tui::GenericTerminal::cursor_save () inline override virtual
Implements tui::ITerminal.
Definition at line 44 of file terminal_generic.cpp.
References write().
cursor_show()
void tui::GenericTerminal::cursor_show () inline override virtual
Implements tui::ITerminal.
Definition at line 36 of file terminal_generic.cpp.
References write().
Referenced by shutdown().
draw_hline()
void tui::GenericTerminal::draw_hline (int x, int y, int w, const Style & style) inline override virtual
Implements tui::ITerminal.
Definition at line 81 of file terminal_generic.cpp.
References write_styled_at().
draw_rect()
void tui::GenericTerminal::draw_rect (int x, int y, int w, int h, const Style & style) inline override virtual
Implements tui::ITerminal.
Definition at line 93 of file terminal_generic.cpp.
References write_styled_at().
draw_vline()
void tui::GenericTerminal::draw_vline (int x, int y, int h, const Style & style) inline override virtual
Implements tui::ITerminal.
Definition at line 87 of file terminal_generic.cpp.
References write_styled_at().
enter_alternate_screen()
void tui::GenericTerminal::enter_alternate_screen () inline override virtual
Implements tui::ITerminal.
Definition at line 124 of file terminal_generic.cpp.
References flush(), and write().
enter_raw_mode()
void tui::GenericTerminal::enter_raw_mode () inline override virtual
Implements tui::ITerminal.
Definition at line 107 of file terminal_generic.cpp.
fill()
void tui::GenericTerminal::fill (int x, int y, int w, int h, char ch, const Style & style) inline override virtual
Implements tui::ITerminal.
Definition at line 70 of file terminal_generic.cpp.
References write_styled_at().
Referenced by clear_region().
flush()
void tui::GenericTerminal::flush () inline override virtual
Implements tui::ITerminal.
Definition at line 32 of file terminal_generic.cpp.
Referenced by enter_alternate_screen(), leave_alternate_screen(), shutdown(), and sync().
init()
bool tui::GenericTerminal::init () inline override virtual
Implements tui::ITerminal.
Definition at line 13 of file terminal_generic.cpp.
leave_alternate_screen()
void tui::GenericTerminal::leave_alternate_screen () inline override virtual
Implements tui::ITerminal.
Definition at line 130 of file terminal_generic.cpp.
References flush(), and write().
Referenced by shutdown().
leave_raw_mode()
void tui::GenericTerminal::leave_raw_mode () inline override virtual
Implements tui::ITerminal.
Definition at line 116 of file terminal_generic.cpp.
Referenced by shutdown().
rows()
int tui::GenericTerminal::rows () const inline override virtual
Implements tui::ITerminal.
Definition at line 48 of file terminal_generic.cpp.
set_title()
void tui::GenericTerminal::set_title (const std::string & title) inline override virtual
Implements tui::ITerminal.
Definition at line 136 of file terminal_generic.cpp.
References write().
shutdown()
void tui::GenericTerminal::shutdown () inline override virtual
Implements tui::ITerminal.
Definition at line 23 of file terminal_generic.cpp.
References cursor_show(), flush(), leave_alternate_screen(), leave_raw_mode(), and write().
sync()
void tui::GenericTerminal::sync () inline override virtual
Implements tui::ITerminal.
Definition at line 33 of file terminal_generic.cpp.
References flush().
term_type()
std::string tui::GenericTerminal::term_type () const inline override virtual
Implements tui::ITerminal.
Definition at line 168 of file terminal_generic.cpp.
write()
void tui::GenericTerminal::write (const std::string & text) inline override virtual
Implements tui::ITerminal.
Definition at line 50 of file terminal_generic.cpp.
Referenced by clear(), cursor_hide(), cursor_move(), cursor_restore(), cursor_save(), cursor_show(), enter_alternate_screen(), leave_alternate_screen(), set_title(), shutdown(), write_at(), and write_styled().
write_at()
void tui::GenericTerminal::write_at (int x, int y, const std::string & text) inline override virtual
Implements tui::ITerminal.
Definition at line 54 of file terminal_generic.cpp.
References cursor_move(), and write().
write_styled()
void tui::GenericTerminal::write_styled (const std::string & text, const Style & style) inline override virtual
Implements tui::ITerminal.
Definition at line 59 of file terminal_generic.cpp.
References write().
Referenced by write_styled_at().
write_styled_at()
void tui::GenericTerminal::write_styled_at (int x, int y, const std::string & text, const Style & style) inline override virtual
Implements tui::ITerminal.
Definition at line 65 of file terminal_generic.cpp.
References cursor_move(), and write_styled().
Referenced by draw_hline(), draw_rect(), draw_vline(), and fill().
The documentation for this class was generated from the following file:
src/platform/terminal_generic.cpp