Desktop TUI: desktop_tui::PluginManager Class Reference
desktop_tui::PluginManager Class Reference
Gestor de plugins dinámicos.
#include <plugin_manager.hpp>
Public Member Functions
PluginManager ()
~PluginManager ()
PluginManager (const PluginManager &)=delete
PluginManager & operator= (const PluginManager &)=delete
PluginResult initialize (const std::string &plugins_dir="./plugins")
Inicializa el gestor de plugins.
PluginResult shutdown ()
Finaliza el gestor y descarga todos los plugins.
PluginResult load_plugin (const std::string &path)
Carga un plugin desde una ruta específica.
PluginResult unload_plugin (const std::string &name)
Descarga un plugin por su nombre.
std::vector< PluginResult > load_all_plugins ()
Carga todos los plugins encontrados en el directorio configurado.
IPlugin * get_plugin (const std::string &name) const
Obtiene un plugin por nombre.
std::vector< std::string > list_plugins () const
Lista todos los plugins cargados.
std::optional< PluginInfo > get_plugin_info (const std::string &name) const
Obtiene información detallada de un plugin.
std::unordered_map< std::string, PluginResult > execute_all ()
Ejecuta todos los plugins activos.
void register_global_callback (const std::string &name, std::function< void()> callback)
Registra un callback global accesible por plugins.
bool trigger_callback (const std::string &name)
Ejecuta un callback global por nombre.
template<typename T >
void set_config (const std::string &key, const T &value)
Establece un valor de configuración.
std::optional< std::any > get_config (const std::string &key) const
Obtiene un valor de configuración.
const std::string & get_plugins_directory () const
Obtiene el directorio de plugins.
bool is_initialized () const
Verifica si el gestor está inicializado.
size_t get_plugin_count () const
Obtiene el número de plugins cargados.
size_t get_active_plugin_count () const
Obtiene el número de plugins activos (inicializados y corriendo)
Detailed Description
Gestor de plugins dinámicos.
Responsable de:
Cargar/descargar plugins desde archivos .so/.dll/.dylib
Mantener el ciclo de vida de los plugins
Proporcionar un contexto seguro para los plugins
Validar dependencias entre plugins
Definition at line 47 of file plugin_manager.hpp.
Constructor & Destructor Documentation
PluginManager() [1/2]
desktop_tui::PluginManager::PluginManager ()
Definition at line 72 of file plugin_manager.cpp.
~PluginManager()
desktop_tui::PluginManager::~PluginManager ()
Definition at line 77 of file plugin_manager.cpp.
References shutdown().
PluginManager() [2/2]
desktop_tui::PluginManager::PluginManager (const PluginManager &) delete
Member Function Documentation
execute_all()
std::unordered_map< std::string, PluginResult > desktop_tui::PluginManager::execute_all ()
Ejecuta todos los plugins activos.
Returns
Resultados de ejecución por plugin
Definition at line 278 of file plugin_manager.cpp.
get_active_plugin_count()
size_t desktop_tui::PluginManager::get_active_plugin_count () const
Obtiene el número de plugins activos (inicializados y corriendo)
Definition at line 326 of file plugin_manager.cpp.
get_config()
std::optional< std::any > desktop_tui::PluginManager::get_config (const std::string & key) const
Obtiene un valor de configuración.
Parameters
key Clave de configuración
Returns
Valor de configuración o nullo si no existe
Definition at line 310 of file plugin_manager.cpp.
Referenced by desktop_tui::PluginContextImpl::get_config().
get_plugin()
IPlugin * desktop_tui::PluginManager::get_plugin (const std::string & name) const
Obtiene un plugin por nombre.
Parameters
name Nombre del plugin
Returns
Puntero al plugin o nullptr si no existe
Definition at line 244 of file plugin_manager.cpp.
get_plugin_count()
size_t desktop_tui::PluginManager::get_plugin_count () const
Obtiene el número de plugins cargados.
Definition at line 321 of file plugin_manager.cpp.
get_plugin_info()
std::optional< PluginInfo > desktop_tui::PluginManager::get_plugin_info (const std::string & name) const
Obtiene información detallada de un plugin.
Parameters
name Nombre del plugin
Returns
Información del plugin o nullo si no existe
Definition at line 267 of file plugin_manager.cpp.
get_plugins_directory()
const std::string & desktop_tui::PluginManager::get_plugins_directory () const inline
Obtiene el directorio de plugins.
Definition at line 150 of file plugin_manager.hpp.
initialize()
PluginResult desktop_tui::PluginManager::initialize (const std::string & plugins_dir = "./plugins")
Inicializa el gestor de plugins.
Parameters
plugins_dir Directorio donde buscar plugins
Returns
Resultado de la inicialización
Definition at line 81 of file plugin_manager.cpp.
References desktop_tui::PluginResult::fail(), and desktop_tui::PluginResult::ok().
is_initialized()
bool desktop_tui::PluginManager::is_initialized () const inline
Verifica si el gestor está inicializado.
Definition at line 155 of file plugin_manager.hpp.
list_plugins()
std::vector< std::string > desktop_tui::PluginManager::list_plugins () const
Lista todos los plugins cargados.
Returns
Vector de nombres de plugins
Definition at line 255 of file plugin_manager.cpp.
load_all_plugins()
std::vector< PluginResult > desktop_tui::PluginManager::load_all_plugins ()
Carga todos los plugins encontrados en el directorio configurado.
Returns
Lista de resultados por cada plugin intentado
Definition at line 210 of file plugin_manager.cpp.
References desktop_tui::PluginResult::fail(), and load_plugin().
load_plugin()
PluginResult desktop_tui::PluginManager::load_plugin (const std::string & path)
Carga un plugin desde una ruta específica.
Parameters
path Ruta al archivo del plugin
Returns
Resultado de la carga
Definition at line 143 of file plugin_manager.cpp.
References desktop_tui::PluginResult::fail(), and desktop_tui::PluginResult::ok().
Referenced by load_all_plugins().
operator=()
PluginManager & desktop_tui::PluginManager::operator= (const PluginManager &) delete
register_global_callback()
void desktop_tui::PluginManager::register_global_callback (const std::string & name, std::function< void()> callback)
Registra un callback global accesible por plugins.
Parameters
name Nombre del callback
callback Función a registrar
Definition at line 292 of file plugin_manager.cpp.
Referenced by desktop_tui::PluginContextImpl::register_callback().
set_config()
template<typename T > void desktop_tui::PluginManager::set_config (const std::string & key, const T & value) inline
Establece un valor de configuración.
Parameters
key Clave de configuración
value Valor a almacenar
Definition at line 135 of file plugin_manager.hpp.
shutdown()
PluginResult desktop_tui::PluginManager::shutdown ()
Finaliza el gestor y descarga todos los plugins.
Definition at line 106 of file plugin_manager.cpp.
References desktop_tui::PluginResult::fail(), desktop_tui::PluginResult::ok(), and unload_plugin().
Referenced by ~PluginManager().
trigger_callback()
bool desktop_tui::PluginManager::trigger_callback (const std::string & name)
Ejecuta un callback global por nombre.
Parameters
name Nombre del callback
Returns
true si el callback existe y fue ejecutado
Definition at line 298 of file plugin_manager.cpp.
unload_plugin()
PluginResult desktop_tui::PluginManager::unload_plugin (const std::string & name)
Descarga un plugin por su nombre.
Parameters
name Nombre del plugin
Returns
Resultado de la descarga
Definition at line 193 of file plugin_manager.cpp.
References desktop_tui::PluginResult::fail().
Referenced by shutdown().
The documentation for this class was generated from the following files:
include/plugins/plugin_manager.hpp
src/plugins/plugin_manager.cpp