Desktop TUI: tui::DesktopManager Class Reference
tui::DesktopManager Class Reference
Manages multiple virtual desktops.
#include <desktop_manager.hpp>
Public Types
using DesktopPtr = std::shared_ptr< Desktop >
Public Member Functions
DesktopManager ()
DesktopManager (int initial_count)
DesktopPtr add_desktop (const std::string &name="")
void remove_desktop (DesktopId id)
bool switch_to (int index)
void switch_next ()
void switch_prev ()
Desktop * active_desktop ()
const Desktop * active_desktop () const
int active_index () const
int desktop_count () const
Desktop * get_desktop (int index)
Desktop * find_desktop (DesktopId id)
const std::vector< DesktopPtr > & all_desktops () const
void move_window_to_desktop (WindowId win_id, int desktop_index)
void render_indicator (Renderer &r, int y)
void render_active_desktop (Renderer &r)
bool dispatch_event (const Event &e)
void on_resize (int cols, int rows)
void on_switched (std::function< void(Desktop &)> cb)
void on_desktop_added (std::function< void(Desktop &)> cb)
Detailed Description
Manages multiple virtual desktops.
Definition at line 15 of file desktop_manager.hpp.
Member Typedef Documentation
DesktopPtr
using tui::DesktopManager::DesktopPtr = std::shared_ptr<Desktop>
Definition at line 17 of file desktop_manager.hpp.
Constructor & Destructor Documentation
DesktopManager() [1/2]
tui::DesktopManager::DesktopManager () inline
Definition at line 19 of file desktop_manager.hpp.
References add_desktop(), and switch_to().
DesktopManager() [2/2]
tui::DesktopManager::DesktopManager (int initial_count) inline explicit
Definition at line 26 of file desktop_manager.hpp.
References add_desktop(), and switch_to().
Member Function Documentation
active_desktop() [1/2]
Desktop * tui::DesktopManager::active_desktop () inline
Definition at line 106 of file desktop_manager.hpp.
Referenced by remove_desktop().
active_desktop() [2/2]
const Desktop * tui::DesktopManager::active_desktop () const inline
Definition at line 107 of file desktop_manager.hpp.
active_index()
int tui::DesktopManager::active_index () const inline
Definition at line 109 of file desktop_manager.hpp.
add_desktop()
DesktopPtr tui::DesktopManager::add_desktop (const std::string & name = "") inline
Definition at line 35 of file desktop_manager.hpp.
Referenced by DesktopManager().
all_desktops()
const std::vector< DesktopPtr > & tui::DesktopManager::all_desktops () const inline
Definition at line 127 of file desktop_manager.hpp.
desktop_count()
int tui::DesktopManager::desktop_count () const inline
Definition at line 110 of file desktop_manager.hpp.
dispatch_event()
bool tui::DesktopManager::dispatch_event (const Event & e) inline
Definition at line 183 of file desktop_manager.hpp.
References tui::Desktop::windows().
find_desktop()
Desktop * tui::DesktopManager::find_desktop (DesktopId id) inline
Definition at line 119 of file desktop_manager.hpp.
get_desktop()
Desktop * tui::DesktopManager::get_desktop (int index) inline
Definition at line 113 of file desktop_manager.hpp.
move_window_to_desktop()
void tui::DesktopManager::move_window_to_desktop (WindowId win_id, int desktop_index) inline
Definition at line 130 of file desktop_manager.hpp.
on_desktop_added()
void tui::DesktopManager::on_desktop_added (std::function< void(Desktop &)> cb) inline
Definition at line 206 of file desktop_manager.hpp.
on_resize()
void tui::DesktopManager::on_resize (int cols, int rows) inline
Definition at line 195 of file desktop_manager.hpp.
Referenced by TUIShell::run().
on_switched()
void tui::DesktopManager::on_switched (std::function< void(Desktop &)> cb) inline
Definition at line 205 of file desktop_manager.hpp.
Referenced by TUIShell::init().
remove_desktop()
void tui::DesktopManager::remove_desktop (DesktopId id) inline
Definition at line 45 of file desktop_manager.hpp.
References active_desktop(), and tui::Desktop::set_active().
render_active_desktop()
void tui::DesktopManager::render_active_desktop (Renderer & r) inline
Definition at line 172 of file desktop_manager.hpp.
References tui::Desktop::windows().
render_indicator()
void tui::DesktopManager::render_indicator (Renderer & r, int y) inline
Definition at line 149 of file desktop_manager.hpp.
References tui::Renderer::cols(), tui::Styles::Dim(), tui::Styles::Normal(), tui::Styles::Title(), and tui::Renderer::write().
switch_next()
void tui::DesktopManager::switch_next () inline
Definition at line 92 of file desktop_manager.hpp.
References switch_to().
switch_prev()
void tui::DesktopManager::switch_prev () inline
Definition at line 99 of file desktop_manager.hpp.
References switch_to().
switch_to()
bool tui::DesktopManager::switch_to (int index) inline
Definition at line 77 of file desktop_manager.hpp.
References tui::Desktop::set_active().
Referenced by DesktopManager(), switch_next(), and switch_prev().
The documentation for this class was generated from the following file:
include/desktop/desktop_manager.hpp