Desktop TUI: desktop_tui::DynamicPlugin Class Reference
desktop_tui::DynamicPlugin Class Reference
Wrapper para plugins cargados dinámicamente.
#include <plugin_interface.hpp>
Public Member Functions
DynamicPlugin (const std::string &path)
~DynamicPlugin ()
DynamicPlugin (const DynamicPlugin &)=delete
DynamicPlugin & operator= (const DynamicPlugin &)=delete
DynamicPlugin (DynamicPlugin &&other) noexcept
DynamicPlugin & operator= (DynamicPlugin &&other) noexcept
PluginResult load ()
Carga el plugin desde la biblioteca compartida.
PluginResult unload ()
Descarga el plugin.
IPlugin * get_instance () const
Obtiene la instancia del plugin.
const std::string & get_path () const
Obtiene la ruta del archivo del plugin.
PluginState get_state () const
Obtiene el estado actual del plugin.
PluginInfo get_info () const
Obtiene la información del plugin.
bool is_loaded () const
Verifica si el plugin está cargado.
bool is_initialized () const
Verifica si el plugin está inicializado.
Detailed Description
Wrapper para plugins cargados dinámicamente.
Definition at line 139 of file plugin_interface.hpp.
Constructor & Destructor Documentation
DynamicPlugin() [1/3]
desktop_tui::DynamicPlugin::DynamicPlugin (const std::string & path)
Definition at line 13 of file dynamic_plugin.cpp.
References desktop_tui::Unloaded.
~DynamicPlugin()
desktop_tui::DynamicPlugin::~DynamicPlugin ()
Definition at line 17 of file dynamic_plugin.cpp.
References unload().
DynamicPlugin() [2/3]
desktop_tui::DynamicPlugin::DynamicPlugin (const DynamicPlugin &) delete
DynamicPlugin() [3/3]
desktop_tui::DynamicPlugin::DynamicPlugin (DynamicPlugin && other) noexcept
Definition at line 21 of file dynamic_plugin.cpp.
References desktop_tui::Unloaded.
Member Function Documentation
get_info()
PluginInfo desktop_tui::DynamicPlugin::get_info () const
Obtiene la información del plugin.
Definition at line 141 of file dynamic_plugin.cpp.
References desktop_tui::PluginInfo::author, desktop_tui::PluginInfo::description, desktop_tui::IPlugin::get_info(), desktop_tui::PluginInfo::name, and desktop_tui::PluginInfo::version.
get_instance()
IPlugin * desktop_tui::DynamicPlugin::get_instance () const inline
Obtiene la instancia del plugin.
Definition at line 163 of file plugin_interface.hpp.
get_path()
const std::string & desktop_tui::DynamicPlugin::get_path () const inline
Obtiene la ruta del archivo del plugin.
Definition at line 168 of file plugin_interface.hpp.
get_state()
PluginState desktop_tui::DynamicPlugin::get_state () const inline
Obtiene el estado actual del plugin.
Definition at line 173 of file plugin_interface.hpp.
is_initialized()
bool desktop_tui::DynamicPlugin::is_initialized () const inline
Verifica si el plugin está inicializado.
Definition at line 188 of file plugin_interface.hpp.
References desktop_tui::Initialized.
is_loaded()
bool desktop_tui::DynamicPlugin::is_loaded () const inline
Verifica si el plugin está cargado.
Definition at line 183 of file plugin_interface.hpp.
References desktop_tui::Loaded.
load()
PluginResult desktop_tui::DynamicPlugin::load ()
Carga el plugin desde la biblioteca compartida.
Definition at line 56 of file dynamic_plugin.cpp.
References desktop_tui::Error, desktop_tui::PluginResult::fail(), desktop_tui::Loaded, desktop_tui::Loading, and desktop_tui::PluginResult::ok().
operator=() [1/2]
DynamicPlugin & desktop_tui::DynamicPlugin::operator= (const DynamicPlugin &) delete
operator=() [2/2]
DynamicPlugin & desktop_tui::DynamicPlugin::operator= (DynamicPlugin && other) noexcept
Definition at line 36 of file dynamic_plugin.cpp.
References desktop_tui::Unloaded.
unload()
PluginResult desktop_tui::DynamicPlugin::unload ()
Descarga el plugin.
Definition at line 110 of file dynamic_plugin.cpp.
References desktop_tui::Error, desktop_tui::PluginResult::fail(), desktop_tui::Initialized, desktop_tui::PluginResult::ok(), desktop_tui::IPlugin::shutdown(), and desktop_tui::Unloaded.
Referenced by ~DynamicPlugin().
The documentation for this class was generated from the following files:
include/plugins/plugin_interface.hpp
src/plugins/dynamic_plugin.cpp