Desktop TUI: tui::Renderer Class Reference
tui::Renderer Class Reference
#include <renderer.hpp>
Public Member Functions
Renderer (ITerminal &term)
void init ()
void resize (int cols, int rows)
void clear ()
void clear_region (int x, int y, int w, int h)
void write (int x, int y, const std::string &text)
void write (int x, int y, const std::string &text, const Style &style)
void put (int x, int y, char32_t ch, const Style &style)
void fill_rect (int x, int y, int w, int h, char32_t ch, const Style &style)
void draw_box (const Rect &rect, const Style &border, const Style &fill)
void draw_border (const Rect &rect, const Style &border)
void write_center (int base_x, int y, const std::string &text, int width, const Style &style)
void write_right (int x, int y, const std::string &text, int max_width, const Style &style)
void flush ()
void mark_dirty ()
void mark_dirty (int, int y, int, int h)
int cols () const
int rows () const
Rect bounds () const
Detailed Description
Double-buffered renderer with dirty-region optimization
Note
THREAD SAFETY: This class is NOT thread-safe. It is designed for single-threaded TUI rendering only. All write(), clear(), flush(), and other mutation operations must occur on the main UI thread.
The renderer uses internal buffers (front_buffer_, back_buffer_) that are not protected by locks. Concurrent access from multiple threads will cause data races and undefined behavior.
Typical usage: All rendering happens in the main loop after event processing.
Definition at line 37 of file renderer.hpp.
Constructor & Destructor Documentation
Renderer()
tui::Renderer::Renderer (ITerminal & term) inline
Definition at line 39 of file renderer.hpp.
Member Function Documentation
bounds()
Rect tui::Renderer::bounds () const inline
Definition at line 329 of file renderer.hpp.
clear()
void tui::Renderer::clear () inline
Definition at line 60 of file renderer.hpp.
References tui::Style::Default().
Referenced by TUIShell::init().
clear_region()
void tui::Renderer::clear_region (int x, int y, int w, int h) inline
Definition at line 68 of file renderer.hpp.
References tui::Style::Default().
cols()
int tui::Renderer::cols () const inline
Definition at line 327 of file renderer.hpp.
Referenced by tui::TextInput::render(), tui::DesktopManager::render_indicator(), and resize().
draw_border()
void tui::Renderer::draw_border (const Rect & rect, const Style & border) inline
Definition at line 194 of file renderer.hpp.
References tui::BoxDrawing, tui::Rect::h, tui::ITerminal::has_cap(), put(), tui::Rect::w, tui::Rect::x, and tui::Rect::y.
Referenced by tui::Border::render().
draw_box()
void tui::Renderer::draw_box (const Rect & rect, const Style & border, const Style & fill) inline
Definition at line 163 of file renderer.hpp.
References tui::BoxDrawing, fill_rect(), tui::Rect::h, tui::ITerminal::has_cap(), put(), tui::Rect::w, tui::Rect::x, and tui::Rect::y.
Referenced by tui::Window::render(), tui::Panel::render(), and tui::TextInput::render().
fill_rect()
void tui::Renderer::fill_rect (int x, int y, int w, int h, char32_t ch, const Style & style) inline
Definition at line 149 of file renderer.hpp.
Referenced by draw_box().
flush()
void tui::Renderer::flush () inline
Definition at line 243 of file renderer.hpp.
References tui::ITerminal::cursor_hide(), tui::ITerminal::cursor_move(), tui::ITerminal::cursor_show(), tui::Style::Default(), tui::ITerminal::flush(), tui::Cell::style, and tui::ITerminal::write().
init()
void tui::Renderer::init () inline
Definition at line 42 of file renderer.hpp.
References tui::ITerminal::cols(), resize(), and tui::ITerminal::rows().
Referenced by TUIShell::init().
mark_dirty() [1/2]
void tui::Renderer::mark_dirty () inline
Definition at line 311 of file renderer.hpp.
Referenced by TUIShell::init(), and TUIShell::run().
mark_dirty() [2/2]
void tui::Renderer::mark_dirty (int , int y, int , int h) inline
Definition at line 314 of file renderer.hpp.
put()
void tui::Renderer::put (int x, int y, char32_t ch, const Style & style) inline
Definition at line 139 of file renderer.hpp.
References tui::Cell::ch, and tui::Cell::style.
Referenced by draw_border(), and draw_box().
resize()
void tui::Renderer::resize (int cols, int rows) inline
Definition at line 47 of file renderer.hpp.
References cols(), and rows().
Referenced by init(), and TUIShell::run().
rows()
int tui::Renderer::rows () const inline
Definition at line 328 of file renderer.hpp.
Referenced by tui::TextInput::render(), and resize().
write() [1/2]
void tui::Renderer::write (int x, int y, const std::string & text) inline
Definition at line 82 of file renderer.hpp.
References tui::Style::Default(), and write().
Referenced by tui::Window::render(), tui::Label::render(), tui::List::render(), tui::Panel::render(), tui::TextInput::render(), tui::DesktopManager::render_indicator(), write(), write_center(), and write_right().
write() [2/2]
void tui::Renderer::write (int x, int y, const std::string & text, const Style & style) inline
Definition at line 87 of file renderer.hpp.
References tui::Cell::ch, tui::is_wide_codepoint(), tui::Cell::style, and tui::utf8_decode().
write_center()
void tui::Renderer::write_center (int base_x, int y, const std::string & text, int width, const Style & style) inline
Definition at line 219 of file renderer.hpp.
References tui::display_width(), tui::truncate(), and write().
Referenced by tui::Label::render().
write_right()
void tui::Renderer::write_right (int x, int y, const std::string & text, int max_width, const Style & style) inline
Definition at line 230 of file renderer.hpp.
References tui::display_width(), tui::truncate(), and write().
Referenced by tui::Label::render().
The documentation for this class was generated from the following file:
include/ui/renderer.hpp