Desktop TUI: desktop_tui::IPlugin Class Reference
desktop_tui::IPlugin Class Reference abstract
Interfaz base que deben implementar todos los plugins.
#include <plugin_interface.hpp>
Public Member Functions
virtual ~IPlugin ()=default
virtual PluginInfo get_info () const =0
Obtiene la información del plugin.
virtual PluginResult initialize (PluginContext &context)=0
Inicializa el plugin con el contexto proporcionado.
virtual PluginResult execute ()=0
Ejecuta el plugin (puede ser llamado repetidamente)
virtual PluginResult shutdown ()=0
Detiene el plugin y libera recursos.
virtual PluginResult handle_command (const std::string &command, const std::vector< std::string > &args)
Maneja comandos personalizados del plugin.
Detailed Description
Interfaz base que deben implementar todos los plugins.
Los plugins deben exportar una función factory: extern "C" IPlugin* create_plugin() y una función destroy: extern "C" void destroy_plugin(IPlugin* plugin)
Definition at line 68 of file plugin_interface.hpp.
Constructor & Destructor Documentation
~IPlugin()
virtual desktop_tui::IPlugin::~IPlugin () virtual default
Member Function Documentation
execute()
virtual PluginResult desktop_tui::IPlugin::execute () pure virtual
Ejecuta el plugin (puede ser llamado repetidamente)
Returns
Resultado de la ejecución
get_info()
virtual PluginInfo desktop_tui::IPlugin::get_info () const pure virtual
Obtiene la información del plugin.
Referenced by desktop_tui::DynamicPlugin::get_info().
handle_command()
virtual PluginResult desktop_tui::IPlugin::handle_command (const std::string & command, const std::vector< std::string > & args) inline virtual
Maneja comandos personalizados del plugin.
Parameters
command Nombre del comando
args Argumentos del comando
Returns
Resultado del comando
Definition at line 101 of file plugin_interface.hpp.
References desktop_tui::PluginResult::fail().
initialize()
virtual PluginResult desktop_tui::IPlugin::initialize (PluginContext & context) pure virtual
Inicializa el plugin con el contexto proporcionado.
Returns
Resultado de la inicialización
shutdown()
virtual PluginResult desktop_tui::IPlugin::shutdown () pure virtual
Detiene el plugin y libera recursos.
Returns
Resultado del shutdown
Referenced by desktop_tui::DynamicPlugin::unload().
The documentation for this class was generated from the following file:
include/plugins/plugin_interface.hpp