Desktop TUI: tui::Window Class Reference
tui::Window Class Reference
A window in the window system.
#include <window.hpp>
Public Member Functions
Window ()
Window (const std::string &title, Rect bounds={})
WindowId id () const
void set_title (const std::string &title)
std::string title () const
void set_bounds (Rect r)
Rect bounds () const
void move (int x, int y)
void resize (int w, int h)
void show ()
void hide ()
bool visible () const
bool is_minimized () const
void minimize ()
void restore ()
void toggle_minimize ()
void focus ()
void blur ()
bool is_focused () const
void set_content (std::shared_ptr< Panel > panel)
std::shared_ptr< Panel > content () const
void render (class Renderer &r)
bool handle_event (const Event &e)
void on_resize (int cols, int rows)
int z_order () const
void set_z_order (int z)
Public Attributes
std::function< void()> on_moved
std::function< void()> on_resized
Detailed Description
A window in the window system.
Definition at line 21 of file window.hpp.
Constructor & Destructor Documentation
Window() [1/2]
tui::Window::Window () inline
Definition at line 23 of file window.hpp.
Window() [2/2]
tui::Window::Window (const std::string & title, Rect bounds = {}) inline explicit
Definition at line 25 of file window.hpp.
Member Function Documentation
blur()
void tui::Window::blur () inline
Definition at line 55 of file window.hpp.
bounds()
Rect tui::Window::bounds () const inline
Definition at line 38 of file window.hpp.
content()
std::shared_ptr< Panel > tui::Window::content () const inline
Definition at line 60 of file window.hpp.
focus()
void tui::Window::focus () inline
Definition at line 54 of file window.hpp.
handle_event()
bool tui::Window::handle_event (const Event & e) inline
Definition at line 90 of file window.hpp.
hide()
void tui::Window::hide () inline
Definition at line 45 of file window.hpp.
id()
WindowId tui::Window::id () const inline
Definition at line 31 of file window.hpp.
is_focused()
bool tui::Window::is_focused () const inline
Definition at line 56 of file window.hpp.
is_minimized()
bool tui::Window::is_minimized () const inline
Definition at line 47 of file window.hpp.
minimize()
void tui::Window::minimize () inline
Definition at line 49 of file window.hpp.
move()
void tui::Window::move (int x, int y) inline
Definition at line 40 of file window.hpp.
References tui::Rect::x, and tui::Rect::y.
on_resize()
void tui::Window::on_resize (int cols, int rows) inline
Definition at line 99 of file window.hpp.
Referenced by resize().
render()
void tui::Window::render (class Renderer & r) inline
Definition at line 63 of file window.hpp.
References tui::Styles::Border(), tui::Styles::BorderActive(), tui::Style::Default(), tui::display_width(), tui::Renderer::draw_box(), tui::Styles::Title(), title(), tui::truncate(), tui::Rect::w, tui::Renderer::write(), tui::Rect::x, and tui::Rect::y.
resize()
void tui::Window::resize (int w, int h) inline
Definition at line 41 of file window.hpp.
References tui::Rect::h, on_resize(), and tui::Rect::w.
restore()
void tui::Window::restore () inline
Definition at line 50 of file window.hpp.
set_bounds()
void tui::Window::set_bounds (Rect r) inline
Definition at line 37 of file window.hpp.
set_content()
void tui::Window::set_content (std::shared_ptr< Panel > panel) inline
Definition at line 59 of file window.hpp.
set_title()
void tui::Window::set_title (const std::string & title) inline
Definition at line 34 of file window.hpp.
References title().
set_z_order()
void tui::Window::set_z_order (int z) inline
Definition at line 106 of file window.hpp.
show()
void tui::Window::show () inline
Definition at line 44 of file window.hpp.
title()
std::string tui::Window::title () const inline
Definition at line 35 of file window.hpp.
Referenced by render(), and set_title().
toggle_minimize()
void tui::Window::toggle_minimize () inline
Definition at line 51 of file window.hpp.
visible()
bool tui::Window::visible () const inline
Definition at line 46 of file window.hpp.
z_order()
int tui::Window::z_order () const inline
Definition at line 105 of file window.hpp.
Member Data Documentation
on_moved
std::function<void()> tui::Window::on_moved
Definition at line 109 of file window.hpp.
on_resized
std::function<void()> tui::Window::on_resized
Definition at line 110 of file window.hpp.
The documentation for this class was generated from the following files:
include/window/window.hpp
src/window/window.cpp