Desktop TUI: tui::TextInput Class Reference
tui::TextInput Class Reference
Widget de entrada de texto de una sola línea con soporte UTF-8.
#include <text_input.hpp>
Public Member Functions
TextInput (const std::string &text="")
~TextInput () override=default
void set_placeholder (const std::string &placeholder)
void set_mask_char (std::optional< char32_t > mask)
void set_max_length (size_t max_len)
const std::string & value () const
void set_value (const std::string &new_value)
bool has_selection () const
std::string selected_text () const
void render (Renderer &renderer) override
bool handle_event (const Event &e) override
void update (double delta_time)
void copy_to_clipboard ()
void cut_to_clipboard ()
void paste_from_clipboard ()
void select_all ()
Public Member Functions inherited from tui::Widget
Widget ()=default
virtual ~Widget ()=default
virtual void set_bounds (const Rect &r)
virtual Rect bounds () const
virtual int x () const
virtual int y () const
virtual int width () const
virtual int height () const
virtual void show ()
virtual void hide ()
virtual bool visible () const
virtual void focus ()
virtual void blur ()
virtual bool focused () const
virtual bool can_focus () const
virtual void set_focusable (bool f)
virtual void render (Renderer &r)=0
virtual bool handle_event (const Event &e)
virtual void on_resize (int cols, int rows)
void on_click (std::function< void()> cb)
Additional Inherited Members
Protected Member Functions inherited from tui::Widget
virtual void on_focus ()
virtual void on_blur ()
void emit_click ()
Protected Attributes inherited from tui::Widget
Rect bounds_
bool visible_ = true
bool focused_ = false
bool focusable_ = false
std::function< void()> on_click_
Detailed Description
Widget de entrada de texto de una sola línea con soporte UTF-8.
Características:
Navegación con flechas, Home, End.
Edición: Insert, Backspace, Delete.
Portapapeles: Ctrl+C (Copiar), Ctrl+X (Cortar), Ctrl+V (Pegar).
Selección de texto con Shift+Flechas o Mouse Drag.
Scroll horizontal automático.
Cursor parpadeante.
Definition at line 35 of file text_input.hpp.
Constructor & Destructor Documentation
TextInput()
tui::TextInput::TextInput (const std::string & text = "") explicit
Definition at line 37 of file text_input.cpp.
~TextInput()
tui::TextInput::~TextInput () override default
Member Function Documentation
copy_to_clipboard()
void tui::TextInput::copy_to_clipboard ()
Definition at line 224 of file text_input.cpp.
References has_selection(), selected_text(), and tui::Clipboard::set().
Referenced by cut_to_clipboard().
cut_to_clipboard()
void tui::TextInput::cut_to_clipboard ()
Definition at line 230 of file text_input.cpp.
References copy_to_clipboard(), and has_selection().
handle_event()
bool tui::TextInput::handle_event (const Event & e) override virtual
Reimplemented from tui::Widget.
Definition at line 378 of file text_input.cpp.
References tui::KeyPress, tui::MouseDown, tui::MouseMove, tui::MouseUp, tui::Event::type, and tui::Widget::visible_.
has_selection()
bool tui::TextInput::has_selection () const inline
Definition at line 48 of file text_input.hpp.
Referenced by copy_to_clipboard(), cut_to_clipboard(), and selected_text().
paste_from_clipboard()
void tui::TextInput::paste_from_clipboard ()
Definition at line 241 of file text_input.cpp.
References tui::Clipboard::get().
render()
void tui::TextInput::render (Renderer & renderer) override virtual
Implements tui::Widget.
Definition at line 397 of file text_input.cpp.
References tui::Style::bg, tui::Style::bold, tui::Widget::bounds_, tui::Renderer::cols(), tui::Style::Default(), tui::display_width(), tui::Renderer::draw_box(), tui::Style::fg, tui::Widget::focused_, tui::Rect::h, tui::Widget::height(), tui::Color::Pal(), tui::Style::reverse, tui::Color::RGB(), tui::Renderer::rows(), tui::truncate(), tui::utf8_decode(), tui::Widget::visible_, tui::Rect::w, tui::Widget::width(), tui::Renderer::write(), tui::Rect::x, tui::Widget::x(), tui::Rect::y, and tui::Widget::y().
select_all()
void tui::TextInput::select_all ()
Definition at line 254 of file text_input.cpp.
selected_text()
std::string tui::TextInput::selected_text () const
Definition at line 64 of file text_input.cpp.
References has_selection().
Referenced by copy_to_clipboard().
set_mask_char()
void tui::TextInput::set_mask_char (std::optional< char32_t > mask)
Definition at line 48 of file text_input.cpp.
set_max_length()
void tui::TextInput::set_max_length (size_t max_len)
Definition at line 52 of file text_input.cpp.
set_placeholder()
void tui::TextInput::set_placeholder (const std::string & placeholder)
Definition at line 44 of file text_input.cpp.
set_value()
void tui::TextInput::set_value (const std::string & new_value)
Definition at line 56 of file text_input.cpp.
update()
void tui::TextInput::update (double delta_time)
Definition at line 497 of file text_input.cpp.
value()
const std::string & tui::TextInput::value () const inline
Definition at line 46 of file text_input.hpp.
The documentation for this class was generated from the following files:
include/ui/text_input.hpp
src/ui/text_input.cpp