Desktop TUI: tui::Panel Class Reference
tui::Panel Class Reference
Panel widget - a container with optional border and title.
#include <panel.hpp>
Public Member Functions
Panel ()
Panel (const std::string &title, const Style &border_style=Styles::Border())
void set_title (const std::string &title)
std::string title () const
void set_border_style (const Style &s)
void set_show_border (bool show)
void add_child (std::shared_ptr< Widget > child)
void remove_child (Widget *child)
void clear_children ()
const std::vector< std::shared_ptr< Widget > > & children () const
Widget * focused_child ()
void render (Renderer &r) override
bool handle_event (const Event &e) override
Rect content_area () const
void on_resize (int cols, int rows) override
Public Member Functions inherited from tui::Widget
Widget ()=default
virtual ~Widget ()=default
virtual void set_bounds (const Rect &r)
virtual Rect bounds () const
virtual int x () const
virtual int y () const
virtual int width () const
virtual int height () const
virtual void show ()
virtual void hide ()
virtual bool visible () const
virtual void focus ()
virtual void blur ()
virtual bool focused () const
virtual bool can_focus () const
virtual void set_focusable (bool f)
virtual void render (Renderer &r)=0
virtual bool handle_event (const Event &e)
virtual void on_resize (int cols, int rows)
void on_click (std::function< void()> cb)
Protected Attributes
std::string title_
Style border_style_
Style fill_style_
bool show_border_ = true
std::vector< std::shared_ptr< Widget > > children_
Protected Attributes inherited from tui::Widget
Rect bounds_
bool visible_ = true
bool focused_ = false
bool focusable_ = false
std::function< void()> on_click_
Additional Inherited Members
Protected Member Functions inherited from tui::Widget
virtual void on_focus ()
virtual void on_blur ()
void emit_click ()
Detailed Description
Panel widget - a container with optional border and title.
Definition at line 13 of file panel.hpp.
Constructor & Destructor Documentation
Panel() [1/2]
tui::Panel::Panel () inline
Definition at line 15 of file panel.hpp.
References tui::Widget::focusable_.
Panel() [2/2]
tui::Panel::Panel (const std::string & title, const Style & border_style = Styles::Border()) inline explicit
Definition at line 17 of file panel.hpp.
References tui::Widget::focusable_.
Member Function Documentation
add_child()
void tui::Panel::add_child (std::shared_ptr< Widget > child) inline
Definition at line 29 of file panel.hpp.
References children_.
children()
const std::vector< std::shared_ptr< Widget > > & tui::Panel::children () const inline
Definition at line 56 of file panel.hpp.
References children_.
clear_children()
void tui::Panel::clear_children () inline
Definition at line 46 of file panel.hpp.
References children_.
content_area()
Rect tui::Panel::content_area () const inline
Definition at line 133 of file panel.hpp.
References tui::Widget::bounds_, tui::Rect::h, show_border_, tui::Rect::w, tui::Rect::x, and tui::Rect::y.
Referenced by render().
focused_child()
Widget * tui::Panel::focused_child () inline
Definition at line 59 of file panel.hpp.
References children_.
Referenced by handle_event().
handle_event()
bool tui::Panel::handle_event (const Event & e) inline override virtual
Reimplemented from tui::Widget.
Definition at line 95 of file panel.hpp.
References tui::Widget::blur(), children_, tui::Rect::contains(), focused_child(), tui::Event::mouse_x, tui::Event::mouse_y, tui::MouseDown, tui::MouseScroll, and tui::Event::type.
on_resize()
void tui::Panel::on_resize (int cols, int rows) inline override virtual
Reimplemented from tui::Widget.
Definition at line 138 of file panel.hpp.
References children_.
remove_child()
void tui::Panel::remove_child (Widget * child) inline
Definition at line 33 of file panel.hpp.
References tui::Widget::blur(), children_, and tui::Widget::focused().
render()
void tui::Panel::render (Renderer & r) inline override virtual
Implements tui::Widget.
Definition at line 66 of file panel.hpp.
References border_style_, tui::Widget::bounds_, children_, content_area(), tui::display_width(), tui::Renderer::draw_box(), fill_style_, tui::Styles::Header(), tui::Rect::intersection(), show_border_, title_, tui::Widget::visible_, tui::Rect::w, tui::Renderer::write(), tui::Rect::x, and tui::Rect::y.
set_border_style()
void tui::Panel::set_border_style (const Style & s) inline
Definition at line 25 of file panel.hpp.
References border_style_.
set_show_border()
void tui::Panel::set_show_border (bool show) inline
Definition at line 26 of file panel.hpp.
References tui::Widget::show(), and show_border_.
set_title()
void tui::Panel::set_title (const std::string & title) inline
Definition at line 22 of file panel.hpp.
References title(), and title_.
title()
std::string tui::Panel::title () const inline
Definition at line 23 of file panel.hpp.
References title_.
Referenced by set_title().
Member Data Documentation
border_style_
Style tui::Panel::border_style_ protected
Definition at line 146 of file panel.hpp.
Referenced by render(), and set_border_style().
children_
std::vector<std::shared_ptr<Widget> > tui::Panel::children_ protected
Definition at line 149 of file panel.hpp.
Referenced by add_child(), children(), clear_children(), focused_child(), handle_event(), on_resize(), remove_child(), and render().
fill_style_
Style tui::Panel::fill_style_ protected
Definition at line 147 of file panel.hpp.
Referenced by render().
show_border_
bool tui::Panel::show_border_ = true protected
Definition at line 148 of file panel.hpp.
Referenced by content_area(), render(), and set_show_border().
title_
std::string tui::Panel::title_ protected
Definition at line 145 of file panel.hpp.
Referenced by render(), set_title(), and title().
The documentation for this class was generated from the following file:
include/ui/panel.hpp