Desktop TUI: tui::WindowsTerminal Class Reference
tui::WindowsTerminal Class Reference
Public Member Functions
WindowsTerminal ()
bool init () override
void shutdown () override
void clear () override
void flush () override
void sync () override
void cursor_hide () override
void cursor_show () override
void cursor_move (int x, int y) override
void cursor_save () override
void cursor_restore () override
int cols () const override
int rows () const override
void write (const std::string &text) override
void write_at (int x, int y, const std::string &text) override
void write_styled (const std::string &text, const Style &style) override
void write_styled_at (int x, int y, const std::string &text, const Style &style) override
void fill (int x, int y, int w, int h, char ch, const Style &style) override
void clear_region (int x, int y, int w, int h) override
void draw_hline (int x, int y, int w, const Style &style) override
void draw_vline (int x, int y, int h, const Style &style) override
void draw_rect (int x, int y, int w, int h, const Style &style) override
void enter_raw_mode () override
void leave_raw_mode () override
void enter_alternate_screen () override
void leave_alternate_screen () override
void set_title (const std::string &title) override
TerminalCaps caps () const override
std::string term_type () const override
Public Member Functions inherited from tui::ITerminal
virtual ~ITerminal ()=default
virtual bool init ()=0
virtual void shutdown ()=0
virtual void clear ()=0
virtual void flush ()=0
virtual void sync ()=0
virtual void cursor_hide ()=0
virtual void cursor_show ()=0
virtual void cursor_move (int x, int y)=0
virtual void cursor_save ()=0
virtual void cursor_restore ()=0
virtual int cols () const =0
virtual int rows () const =0
virtual Rect bounds () const
virtual void write (const std::string &text)=0
virtual void write_at (int x, int y, const std::string &text)=0
virtual void write_styled (const std::string &text, const Style &style)=0
virtual void write_styled_at (int x, int y, const std::string &text, const Style &style)=0
virtual void fill (int x, int y, int w, int h, char ch, const Style &style)=0
virtual void clear_region (int x, int y, int w, int h)=0
virtual void draw_hline (int x, int y, int w, const Style &style)=0
virtual void draw_vline (int x, int y, int h, const Style &style)=0
virtual void draw_rect (int x, int y, int w, int h, const Style &style)=0
virtual void draw_box (int x, int y, int w, int h, const Style &border_style, const Style &fill_style)
virtual void enter_raw_mode ()=0
virtual void leave_raw_mode ()=0
virtual void enter_alternate_screen ()=0
virtual void leave_alternate_screen ()=0
virtual void set_title (const std::string &title)=0
virtual TerminalCaps caps () const =0
virtual bool has_cap (TerminalCaps cap) const
virtual std::string term_type () const =0
virtual bool check_resize (int &new_cols, int &new_rows)
Detailed Description
Definition at line 16 of file terminal_win.cpp.
Constructor & Destructor Documentation
WindowsTerminal()
tui::WindowsTerminal::WindowsTerminal () inline
Definition at line 18 of file terminal_win.cpp.
Member Function Documentation
caps()
TerminalCaps tui::WindowsTerminal::caps () const inline override virtual
Implements tui::ITerminal.
Definition at line 275 of file terminal_win.cpp.
References tui::AnsiColors, tui::BoxDrawing, tui::Color256, tui::Mouse, tui::Resize, tui::TrueColor, and tui::Unicode.
clear()
void tui::WindowsTerminal::clear () inline override virtual
Implements tui::ITerminal.
Definition at line 64 of file terminal_win.cpp.
References write().
clear_region()
void tui::WindowsTerminal::clear_region (int x, int y, int w, int h) inline override virtual
Implements tui::ITerminal.
Definition at line 163 of file terminal_win.cpp.
References tui::Style::Default(), and fill().
cols()
int tui::WindowsTerminal::cols () const inline override virtual
Implements tui::ITerminal.
Definition at line 104 of file terminal_win.cpp.
cursor_hide()
void tui::WindowsTerminal::cursor_hide () inline override virtual
Implements tui::ITerminal.
Definition at line 80 of file terminal_win.cpp.
References write().
cursor_move()
void tui::WindowsTerminal::cursor_move (int x, int y) inline override virtual
Implements tui::ITerminal.
Definition at line 90 of file terminal_win.cpp.
References write().
Referenced by write_at(), and write_styled_at().
cursor_restore()
void tui::WindowsTerminal::cursor_restore () inline override virtual
Implements tui::ITerminal.
Definition at line 102 of file terminal_win.cpp.
References write().
cursor_save()
void tui::WindowsTerminal::cursor_save () inline override virtual
Implements tui::ITerminal.
Definition at line 101 of file terminal_win.cpp.
References write().
cursor_show()
void tui::WindowsTerminal::cursor_show () inline override virtual
Implements tui::ITerminal.
Definition at line 85 of file terminal_win.cpp.
References write().
Referenced by shutdown().
draw_hline()
void tui::WindowsTerminal::draw_hline (int x, int y, int w, const Style & style) inline override virtual
Implements tui::ITerminal.
Definition at line 167 of file terminal_win.cpp.
References write_styled_at().
draw_rect()
void tui::WindowsTerminal::draw_rect (int x, int y, int w, int h, const Style & style) inline override virtual
Implements tui::ITerminal.
Definition at line 182 of file terminal_win.cpp.
References write_styled_at().
draw_vline()
void tui::WindowsTerminal::draw_vline (int x, int y, int h, const Style & style) inline override virtual
Implements tui::ITerminal.
Definition at line 175 of file terminal_win.cpp.
References write_styled_at().
enter_alternate_screen()
void tui::WindowsTerminal::enter_alternate_screen () inline override virtual
Implements tui::ITerminal.
Definition at line 232 of file terminal_win.cpp.
References flush(), and write().
enter_raw_mode()
void tui::WindowsTerminal::enter_raw_mode () inline override virtual
Implements tui::ITerminal.
Definition at line 204 of file terminal_win.cpp.
References write().
fill()
void tui::WindowsTerminal::fill (int x, int y, int w, int h, char ch, const Style & style) inline override virtual
Implements tui::ITerminal.
Definition at line 138 of file terminal_win.cpp.
References tui::ColorRGB::b, tui::Style::bold, tui::Style::fg, tui::ColorRGB::g, tui::Color::mode, tui::ColorRGB::r, tui::Color::rgb, tui::Color::TrueColor, and write_styled_at().
Referenced by clear_region().
flush()
void tui::WindowsTerminal::flush () inline override virtual
Implements tui::ITerminal.
Definition at line 77 of file terminal_win.cpp.
Referenced by enter_alternate_screen(), leave_alternate_screen(), shutdown(), and sync().
init()
bool tui::WindowsTerminal::init () inline override virtual
Implements tui::ITerminal.
Definition at line 38 of file terminal_win.cpp.
leave_alternate_screen()
void tui::WindowsTerminal::leave_alternate_screen () inline override virtual
Implements tui::ITerminal.
Definition at line 240 of file terminal_win.cpp.
References flush(), and write().
Referenced by shutdown().
leave_raw_mode()
void tui::WindowsTerminal::leave_raw_mode () inline override virtual
Implements tui::ITerminal.
Definition at line 224 of file terminal_win.cpp.
References write().
Referenced by shutdown().
rows()
int tui::WindowsTerminal::rows () const inline override virtual
Implements tui::ITerminal.
Definition at line 105 of file terminal_win.cpp.
set_title()
void tui::WindowsTerminal::set_title (const std::string & title) inline override virtual
Implements tui::ITerminal.
Definition at line 248 of file terminal_win.cpp.
shutdown()
void tui::WindowsTerminal::shutdown () inline override virtual
Implements tui::ITerminal.
Definition at line 56 of file terminal_win.cpp.
References cursor_show(), flush(), leave_alternate_screen(), leave_raw_mode(), and write().
sync()
void tui::WindowsTerminal::sync () inline override virtual
Implements tui::ITerminal.
Definition at line 78 of file terminal_win.cpp.
References flush().
term_type()
std::string tui::WindowsTerminal::term_type () const inline override virtual
Implements tui::ITerminal.
Definition at line 284 of file terminal_win.cpp.
write()
void tui::WindowsTerminal::write (const std::string & text) inline override virtual
Implements tui::ITerminal.
Definition at line 107 of file terminal_win.cpp.
Referenced by clear(), cursor_hide(), cursor_move(), cursor_restore(), cursor_save(), cursor_show(), enter_alternate_screen(), enter_raw_mode(), leave_alternate_screen(), leave_raw_mode(), shutdown(), write_at(), and write_styled().
write_at()
void tui::WindowsTerminal::write_at (int x, int y, const std::string & text) inline override virtual
Implements tui::ITerminal.
Definition at line 117 of file terminal_win.cpp.
References cursor_move(), and write().
write_styled()
void tui::WindowsTerminal::write_styled (const std::string & text, const Style & style) inline override virtual
Implements tui::ITerminal.
Definition at line 122 of file terminal_win.cpp.
References write().
Referenced by write_styled_at().
write_styled_at()
void tui::WindowsTerminal::write_styled_at (int x, int y, const std::string & text, const Style & style) inline override virtual
Implements tui::ITerminal.
Definition at line 133 of file terminal_win.cpp.
References cursor_move(), and write_styled().
Referenced by draw_hline(), draw_rect(), draw_vline(), and fill().
The documentation for this class was generated from the following file:
src/platform/terminal_win.cpp