Desktop TUI: tui::Desktop Class Reference
tui::Desktop Class Reference
#include <desktop.hpp>
Public Member Functions
Desktop ()
Desktop (const std::string &name)
DesktopId id () const
void set_name (const std::string &name)
std::string name () const
bool is_active () const
void set_active (bool a)
void add_window (std::shared_ptr< Window > win)
void remove_window (WindowId id)
const std::vector< std::shared_ptr< Window > > & windows ()
Window * find_window (WindowId id)
bool has_window (WindowId id) const
int window_count () const
void move_to_desktop (WindowId id, Desktop &target)
void on_resize (int cols, int rows)
Detailed Description
A virtual desktop containing windows Desktops track window membership but do NOT own windows (WindowManager owns them)
Definition at line 18 of file desktop.hpp.
Constructor & Destructor Documentation
Desktop() [1/2]
tui::Desktop::Desktop () inline
Definition at line 20 of file desktop.hpp.
Desktop() [2/2]
tui::Desktop::Desktop (const std::string & name) inline explicit
Definition at line 22 of file desktop.hpp.
Member Function Documentation
add_window()
void tui::Desktop::add_window (std::shared_ptr< Window > win) inline
Definition at line 34 of file desktop.hpp.
Referenced by move_to_desktop().
find_window()
Window * tui::Desktop::find_window (WindowId id) inline
Definition at line 58 of file desktop.hpp.
has_window()
bool tui::Desktop::has_window (WindowId id) const inline
Definition at line 65 of file desktop.hpp.
id()
DesktopId tui::Desktop::id () const inline
Definition at line 25 of file desktop.hpp.
is_active()
bool tui::Desktop::is_active () const inline
Definition at line 30 of file desktop.hpp.
move_to_desktop()
void tui::Desktop::move_to_desktop (WindowId id, Desktop & target) inline
Definition at line 72 of file desktop.hpp.
References add_window().
name()
std::string tui::Desktop::name () const inline
Definition at line 28 of file desktop.hpp.
Referenced by set_name().
on_resize()
void tui::Desktop::on_resize (int cols, int rows) inline
Definition at line 84 of file desktop.hpp.
References tui::Rect::h, tui::Rect::w, tui::Rect::x, and tui::Rect::y.
remove_window()
void tui::Desktop::remove_window (WindowId id) inline
Definition at line 42 of file desktop.hpp.
set_active()
void tui::Desktop::set_active (bool a) inline
Definition at line 31 of file desktop.hpp.
Referenced by tui::DesktopManager::remove_desktop(), and tui::DesktopManager::switch_to().
set_name()
void tui::Desktop::set_name (const std::string & name) inline
Definition at line 27 of file desktop.hpp.
References name().
window_count()
int tui::Desktop::window_count () const inline
Definition at line 69 of file desktop.hpp.
windows()
const std::vector< std::shared_ptr< Window > > & tui::Desktop::windows () inline
Definition at line 52 of file desktop.hpp.
Referenced by tui::DesktopManager::dispatch_event(), and tui::DesktopManager::render_active_desktop().
The documentation for this class was generated from the following files:
include/desktop/desktop.hpp
src/desktop/desktop.cpp