Desktop TUI: TUIShell Class Reference
TUIShell Class Reference
TUI Shell - the main application controller.
Public Member Functions
TUIShell ()
~TUIShell ()
bool init ()
void shutdown ()
void run ()
Detailed Description
TUI Shell - the main application controller.
Definition at line 32 of file main.cpp.
Constructor & Destructor Documentation
TUIShell()
TUIShell::TUIShell () inline
Definition at line 34 of file main.cpp.
~TUIShell()
TUIShell::~TUIShell () inline
Definition at line 41 of file main.cpp.
References shutdown().
Member Function Documentation
init()
bool TUIShell::init () inline
Definition at line 45 of file main.cpp.
References tui::Renderer::clear(), tui::ITerminal::cursor_hide(), tui::ITerminal::enter_alternate_screen(), tui::ITerminal::enter_raw_mode(), tui::Renderer::init(), tui::IInput::init(), tui::ITerminal::init(), tui::Renderer::mark_dirty(), tui::DesktopManager::on_switched(), tui::ITerminal::set_title(), and signal_handler().
Referenced by main().
run()
void TUIShell::run () inline
Definition at line 103 of file main.cpp.
References tui::ITerminal::check_resize(), g_running, tui::Renderer::mark_dirty(), tui::DesktopManager::on_resize(), and tui::Renderer::resize().
Referenced by main().
shutdown()
void TUIShell::shutdown () inline
Definition at line 87 of file main.cpp.
References tui::ITerminal::cursor_show(), tui::destroy_input(), tui::destroy_terminal(), tui::ITerminal::leave_alternate_screen(), tui::ITerminal::leave_raw_mode(), and tui::ITerminal::shutdown().
Referenced by ~TUIShell().
The documentation for this class was generated from the following file:
src/main.cpp