Desktop TUI: tui Namespace Reference
tui Namespace Reference
Namespaces
namespace Keys
namespace Styles
Predefined styles.
Classes
class Border
Border widget - draws a bordered rectangle.
struct Cell
A single cell in the render buffer.
class Clipboard
class ClipboardImpl
struct Color
Color representation (index or true color)
struct ColorRGB
True color RGB.
struct Config
class Desktop
class DesktopManager
Manages multiple virtual desktops.
struct Event
class EventBus
class GenericInput
class GenericTerminal
class IInput
Abstract input handler interface.
class ITerminal
Abstract terminal interface.
struct KeyMods
class Label
Label widget - displays text.
class List
List widget - scrollable list of items.
class Logger
class Panel
Panel widget - a container with optional border and title.
struct Point
class PosixInput
class PosixTerminal
struct Rect
class Renderer
class Signal
struct Style
class TextInput
Widget de entrada de texto de una sola línea con soporte UTF-8.
class Widget
Base widget class.
class Window
A window in the window system.
class WindowsInput
class WindowsTerminal
Typedefs
using ColorIndex = uint8_t
256-color palette index
using EventHandler = std::function< void(const Event &)>
using DesktopId = uint32_t
using WindowId = uint64_t
Enumerations
enum class EventType {
KeyPress ,
KeyRelease ,
MouseDown ,
MouseUp ,
MouseMove ,
MouseScroll ,
Resize ,
FocusIn ,
FocusOut ,
DesktopSwitch ,
WindowCreate ,
WindowClose ,
WindowFocus ,
WindowMove ,
WindowResize ,
Quit ,
Custom
}
enum class LogLevel : int {
DEBUG = 0 ,
INFO = 1 ,
WARN = 2 ,
ERROR = 3 ,
OFF = 4
}
Log levels.
enum class TerminalCaps : uint8_t {
None = 0 ,
AnsiColors = 1 << 0 ,
Color256 = 1 << 1 ,
TrueColor = 1 << 2 ,
Mouse = 1 << 3 ,
Unicode = 1 << 4 ,
BoxDrawing = 1 << 5 ,
Resize = 1 << 6
}
Terminal capability flags.
Functions
std::string emit_style_to_string (const Style &style)
DRY: Generate ANSI escape sequence for a Style (shared across all terminals)
char32_t utf8_decode (const char *&p, const char *end)
bool is_wide_codepoint (char32_t ch)
size_t display_width (const std::string &utf8_str)
std::string truncate (const std::string &utf8_str, size_t max_width)
std::vector< std::string > split (const std::string &s, char delim)
Split a string by delimiter.
std::string trim (const std::string &s)
Trim whitespace from both ends.
std::string pad (const std::string &s, size_t width, char fill=' ')
Pad or truncate string to given display width.
std::string center (const std::string &s, size_t width, char fill=' ')
Center text within given display width.
std::string right_align (const std::string &s, size_t width, char fill=' ')
Right-align text within given display width.
std::string repeat (const std::string &s, size_t n)
Repeat a string n times.
std::string replace_all (std::string str, const std::string &from, const std::string &to)
Replace all occurrences of 'from' with 'to'.
std::string join (const std::vector< std::string > &parts, const std::string &sep)
Join vector of strings with separator.
template<typename T >
std::string to_str (T val)
Convert integer to string (shorthand)
std::vector< std::string > word_wrap (const std::string &text, size_t width)
Wrap text to multiple lines at given display width.
IInput * create_input ()
Factory: create the appropriate input handler for this platform.
void destroy_input (IInput *input)
TerminalCaps operator| (TerminalCaps a, TerminalCaps b)
TerminalCaps operator& (TerminalCaps a, TerminalCaps b)
ITerminal * create_terminal ()
Factory: create the appropriate terminal for this platform.
void destroy_terminal (ITerminal *term)
Variables
static constexpr std::pair< char32_t, char32_t > wide_ranges []
static std::atomic< bool > g_resize_pending {false}
static std::atomic< bool > g_is_initialized {false}
Typedef Documentation
ColorIndex
using tui::ColorIndex = typedef uint8_t
256-color palette index
Definition at line 10 of file colors.hpp.
DesktopId
using tui::DesktopId = typedef uint32_t
Definition at line 14 of file desktop.hpp.
EventHandler
using tui::EventHandler = typedef std::function<void(const Event&)>
Definition at line 105 of file event.hpp.
WindowId
using tui::WindowId = typedef uint64_t
Definition at line 18 of file window.hpp.
Enumeration Type Documentation
EventType
enum class tui::EventType strong
Enumerator
KeyPress
KeyRelease
MouseDown
MouseUp
MouseMove
MouseScroll
Resize
FocusIn
FocusOut
DesktopSwitch
WindowCreate
WindowClose
WindowFocus
WindowMove
WindowResize
Quit
Custom
Definition at line 13 of file event.hpp.
LogLevel
enum class tui::LogLevel : int strong
Log levels.
Enumerator
DEBUG
INFO
WARN
ERROR
OFF
Definition at line 12 of file logger.hpp.
TerminalCaps
enum class tui::TerminalCaps : uint8_t strong
Terminal capability flags.
Enumerator
None
AnsiColors
Color256
TrueColor
Mouse
Unicode
BoxDrawing
Resize
Definition at line 12 of file terminal.hpp.
Function Documentation
center()
std::string tui::center (const std::string & s, size_t width, char fill = ' ') inline
Center text within given display width.
Definition at line 169 of file string_utils.hpp.
References display_width(), and truncate().
create_input()
IInput * tui::create_input ()
Factory: create the appropriate input handler for this platform.
Definition at line 78 of file input_generic.cpp.
create_terminal()
ITerminal * tui::create_terminal ()
Factory: create the appropriate terminal for this platform.
Definition at line 179 of file terminal_generic.cpp.
destroy_input()
void tui::destroy_input (IInput * input)
Definition at line 82 of file input_generic.cpp.
Referenced by TUIShell::shutdown().
destroy_terminal()
void tui::destroy_terminal (ITerminal * term)
Definition at line 183 of file terminal_generic.cpp.
Referenced by TUIShell::shutdown().
display_width()
size_t tui::display_width (const std::string & utf8_str) inline
Count visible display width of a UTF-8 string Handles CJK wide characters (which take 2 cells)
Definition at line 78 of file string_utils.hpp.
References is_wide_codepoint(), and utf8_decode().
Referenced by center(), pad(), tui::Window::render(), tui::List::render(), tui::Panel::render(), tui::TextInput::render(), right_align(), truncate(), word_wrap(), tui::Renderer::write_center(), and tui::Renderer::write_right().
emit_style_to_string()
std::string tui::emit_style_to_string (const Style & style) inline
DRY: Generate ANSI escape sequence for a Style (shared across all terminals)
Definition at line 126 of file colors.hpp.
References tui::ColorRGB::b, tui::Style::bg, tui::Style::blink, tui::Style::bold, tui::Style::dim, tui::Style::fg, tui::ColorRGB::g, tui::Style::hidden, tui::Color::index, tui::Color::Indexed, tui::Style::italic, tui::Color::mode, tui::ColorRGB::r, tui::Style::reverse, tui::Color::rgb, tui::Color::TrueColor, and tui::Style::underline.
is_wide_codepoint()
bool tui::is_wide_codepoint (char32_t ch) inline
Check if a codepoint has display width 2 (CJK, Hangul, etc.) Uses binary search on pre-sorted ranges for O(log n) performance
Definition at line 58 of file string_utils.hpp.
References wide_ranges.
Referenced by display_width(), truncate(), and tui::Renderer::write().
join()
std::string tui::join (const std::vector< std::string > & parts, const std::string & sep) inline
Join vector of strings with separator.
Definition at line 205 of file string_utils.hpp.
operator&()
TerminalCaps tui::operator& (TerminalCaps a, TerminalCaps b) inline
Definition at line 26 of file terminal.hpp.
operator|()
TerminalCaps tui::operator| (TerminalCaps a, TerminalCaps b) inline
Definition at line 23 of file terminal.hpp.
pad()
std::string tui::pad (const std::string & s, size_t width, char fill = ' ') inline
Pad or truncate string to given display width.
Definition at line 162 of file string_utils.hpp.
References display_width(), and truncate().
repeat()
std::string tui::repeat (const std::string & s, size_t n) inline
Repeat a string n times.
Definition at line 186 of file string_utils.hpp.
replace_all()
std::string tui::replace_all (std::string str, const std::string & from, const std::string & to) inline
Replace all occurrences of 'from' with 'to'.
Definition at line 194 of file string_utils.hpp.
right_align()
std::string tui::right_align (const std::string & s, size_t width, char fill = ' ') inline
Right-align text within given display width.
Definition at line 179 of file string_utils.hpp.
References display_width(), and truncate().
split()
std::vector< std::string > tui::split (const std::string & s, char delim) inline
Split a string by delimiter.
Definition at line 140 of file string_utils.hpp.
to_str()
template<typename T > std::string tui::to_str (T val)
Convert integer to string (shorthand)
Definition at line 216 of file string_utils.hpp.
trim()
std::string tui::trim (const std::string & s) inline
Trim whitespace from both ends.
Definition at line 151 of file string_utils.hpp.
truncate()
std::string tui::truncate (const std::string & utf8_str, size_t max_width) inline
Truncate UTF-8 string to display width (UTF-8 aware) Safely handles CJK wide characters and avoids cutting mid-codepoint
Definition at line 99 of file string_utils.hpp.
References display_width(), is_wide_codepoint(), and utf8_decode().
Referenced by center(), pad(), tui::Window::render(), tui::List::render(), tui::TextInput::render(), right_align(), tui::Renderer::write_center(), and tui::Renderer::write_right().
utf8_decode()
char32_t tui::utf8_decode (const char *& p, const char * end) inline
Decode a single UTF-8 codepoint from the given pointer. Advances p past the consumed bytes. Returns 0 on invalid input.
Definition at line 14 of file string_utils.hpp.
Referenced by display_width(), tui::TextInput::render(), truncate(), and tui::Renderer::write().
word_wrap()
std::vector< std::string > tui::word_wrap (const std::string & text, size_t width) inline
Wrap text to multiple lines at given display width.
Definition at line 221 of file string_utils.hpp.
References display_width().
Referenced by tui::Label::render().
Variable Documentation
g_is_initialized
std::atomic<bool> tui::g_is_initialized {false} static
Definition at line 23 of file terminal_posix.cpp.
Referenced by tui::PosixTerminal::init(), and tui::PosixTerminal::~PosixTerminal().
g_resize_pending
std::atomic<bool> tui::g_resize_pending {false} static
Definition at line 20 of file terminal_posix.cpp.
Referenced by tui::PosixTerminal::check_resize().
wide_ranges
constexpr std::pair<char32_t, char32_t> tui::wide_ranges[] static constexpr
Initial value:
= {
    {0x1100, 0x115F},
    {0x2E80, 0x2EFF},
    {0x3040, 0x309F},
    {0x30A0, 0x30FF},
    {0x31C0, 0x31EF},
    {0x3400, 0x4DBF},
    {0x4E00, 0x9FFF},
    {0xAC00, 0xD7AF},
    {0xF900, 0xFAFF},
    {0xFF01, 0xFF60},
    {0xFFE0, 0xFFE6},
    {0x20000, 0x2A6DF},
    {0x2A700, 0x2B73F},
    {0x2B740, 0x2B81F},
    {0x2B820, 0x2CEAF},
    {0x2F800, 0x2FA1F},
}
Definition at line 37 of file string_utils.hpp.
Referenced by is_wide_codepoint().