Desktop TUI: tui::Styles Namespace Reference
tui::Styles Namespace Reference
Predefined styles.
Functions
Style Normal ()
Style Bold ()
Style Title ()
Style Header ()
Style Success ()
Style Error ()
Style Warning ()
Style Info ()
Style Dim ()
Style Selected ()
Style Border ()
Style BorderActive ()
Detailed Description
Predefined styles.
Function Documentation
Bold()
Style tui::Styles::Bold () inline
Definition at line 112 of file colors.hpp.
References tui::Style::bold.
Border()
Style tui::Styles::Border () inline
Definition at line 121 of file colors.hpp.
References tui::Style::fg, and tui::Color::Pal().
Referenced by tui::Window::render().
BorderActive()
Style tui::Styles::BorderActive () inline
Definition at line 122 of file colors.hpp.
References tui::Style::bold, tui::Style::fg, and tui::Color::Pal().
Referenced by tui::Window::render().
Dim()
Style tui::Styles::Dim () inline
Definition at line 119 of file colors.hpp.
References tui::Style::dim.
Referenced by tui::List::render(), and tui::DesktopManager::render_indicator().
Error()
Style tui::Styles::Error () inline
Definition at line 116 of file colors.hpp.
References tui::Style::fg, and tui::Color::Pal().
Header()
Style tui::Styles::Header () inline
Definition at line 114 of file colors.hpp.
References tui::Style::bold, tui::Style::fg, and tui::Color::Pal().
Referenced by tui::Panel::render().
Info()
Style tui::Styles::Info () inline
Definition at line 118 of file colors.hpp.
References tui::Style::fg, and tui::Color::Pal().
Normal()
Style tui::Styles::Normal () inline
Definition at line 111 of file colors.hpp.
References tui::Style::Default().
Referenced by tui::DesktopManager::render_indicator().
Selected()
Style tui::Styles::Selected () inline
Definition at line 120 of file colors.hpp.
References tui::Style::reverse.
Referenced by tui::List::render().
Success()
Style tui::Styles::Success () inline
Definition at line 115 of file colors.hpp.
References tui::Style::fg, and tui::Color::Pal().
Title()
Style tui::Styles::Title () inline
Definition at line 113 of file colors.hpp.
References tui::Style::bold, tui::Style::fg, and tui::Color::Pal().
Referenced by tui::Window::render(), and tui::DesktopManager::render_indicator().
Warning()
Style tui::Styles::Warning () inline
Definition at line 117 of file colors.hpp.
References tui::Style::fg, and tui::Color::Pal().