Desktop TUI: desktop_tui::PluginResult Struct Reference
desktop_tui::PluginResult Struct Reference
Resultado de operaciones de plugins.
#include <plugin_interface.hpp>
Static Public Member Functions
static PluginResult ok (const std::string &msg="OK")
static PluginResult fail (const std::string &msg, int code=1)
Public Attributes
bool success
std::string message
int error_code = 0
Detailed Description
Resultado de operaciones de plugins.
Definition at line 48 of file plugin_interface.hpp.
Member Function Documentation
fail()
static PluginResult desktop_tui::PluginResult::fail (const std::string & msg, int code = 1) inline static
Definition at line 57 of file plugin_interface.hpp.
Referenced by desktop_tui::IPlugin::handle_command(), desktop_tui::PluginManager::initialize(), desktop_tui::DynamicPlugin::load(), desktop_tui::PluginManager::load_all_plugins(), desktop_tui::PluginManager::load_plugin(), desktop_tui::PluginManager::shutdown(), desktop_tui::DynamicPlugin::unload(), and desktop_tui::PluginManager::unload_plugin().
ok()
static PluginResult desktop_tui::PluginResult::ok (const std::string & msg = "OK") inline static
Definition at line 53 of file plugin_interface.hpp.
Referenced by desktop_tui::PluginManager::initialize(), desktop_tui::DynamicPlugin::load(), desktop_tui::PluginManager::load_plugin(), desktop_tui::PluginManager::shutdown(), and desktop_tui::DynamicPlugin::unload().
Member Data Documentation
error_code
int desktop_tui::PluginResult::error_code = 0
Definition at line 51 of file plugin_interface.hpp.
message
std::string desktop_tui::PluginResult::message
Definition at line 50 of file plugin_interface.hpp.
success
bool desktop_tui::PluginResult::success
Definition at line 49 of file plugin_interface.hpp.
The documentation for this struct was generated from the following file:
include/plugins/plugin_interface.hpp