Desktop TUI: tui::Color Struct Reference
tui::Color Struct Reference
Color representation (index or true color)
#include <colors.hpp>
Public Types
enum class Mode {
Default ,
Indexed ,
TrueColor
}
Public Member Functions
Color ()
Static Public Member Functions
static Color DefaultColor ()
static Color Pal (ColorIndex i)
static Color RGB (uint8_t r, uint8_t g, uint8_t b)
static Color RGB (ColorRGB c)
Public Attributes
Mode mode
union {
ColorIndex index
ColorRGB rgb
};
Detailed Description
Color representation (index or true color)
Definition at line 37 of file colors.hpp.
Member Enumeration Documentation
Mode
enum class tui::Color::Mode strong
Enumerator
Default
Indexed
TrueColor
Definition at line 38 of file colors.hpp.
Constructor & Destructor Documentation
Color()
tui::Color::Color () inline
Definition at line 46 of file colors.hpp.
Member Function Documentation
DefaultColor()
static Color tui::Color::DefaultColor () inline static
Definition at line 47 of file colors.hpp.
References Default, and mode.
Pal()
static Color tui::Color::Pal (ColorIndex i) inline static
Definition at line 48 of file colors.hpp.
References index, Indexed, and mode.
Referenced by tui::Styles::Border(), tui::Styles::BorderActive(), tui::Styles::Error(), tui::Styles::Header(), tui::Styles::Info(), tui::TextInput::render(), tui::Styles::Success(), tui::Styles::Title(), and tui::Styles::Warning().
RGB() [1/2]
static Color tui::Color::RGB (ColorRGB c) inline static
Definition at line 54 of file colors.hpp.
References mode, rgb, and TrueColor.
RGB() [2/2]
static Color tui::Color::RGB (uint8_t r, uint8_t g, uint8_t b) inline static
Definition at line 51 of file colors.hpp.
References mode, rgb, and TrueColor.
Referenced by tui::TextInput::render().
Member Data Documentation
union { ... } tui::Color::@1
index
ColorIndex tui::Color::index
Definition at line 42 of file colors.hpp.
Referenced by tui::emit_style_to_string(), tui::Style::operator==(), and Pal().
mode
Mode tui::Color::mode
Definition at line 40 of file colors.hpp.
Referenced by DefaultColor(), tui::emit_style_to_string(), tui::WindowsTerminal::fill(), tui::Style::operator==(), Pal(), and RGB().
rgb
ColorRGB tui::Color::rgb
Definition at line 43 of file colors.hpp.
Referenced by tui::emit_style_to_string(), tui::WindowsTerminal::fill(), tui::Style::operator==(), and RGB().
The documentation for this struct was generated from the following file:
include/core/colors.hpp